### ISSUE TITLE
provide more detailed error message on OIDC failure

### ISSUE THREAD

**Issue by benkroeger** [AzureAD/passport-azure-ad#104]
Azure AD provides quite a lot of information when the OAuth dance fails. Several error properties are provided as `error_*` prefixed query parameter in the callback redirect.
Unfortunately, the OidcStrategy only provides the `error` parameter back to passport

**Comment by lovemaths** [comment]
We capture err_description and put it in log, maybe need to capture err_uri ( #166 ), closing the issue.
