### ISSUE TITLE
use proper XML library

### ISSUE THREAD

**Issue by benkroeger** [AzureAD/passport-azure-ad#106]
there are fixed XML DOM navigations in this code that might break if child-nodes come in a different order.
There are libraries that support XML Parsing / Stringify along with proper XPath selectors that should make your life much easier. Take a look at [oniyi-utils-xml](https://www.npmjs.com/package/oniyi-utils-xml) which is, I have to admit, badly documented - but does everything this module needs wrt XML documents

**Comment by polita** [comment]
Please reopen if this manifests in an actual issue.
