### ISSUE TITLE
remove bunyan dependency

### ISSUE THREAD

**Issue by benkroeger** [AzureAD/passport-azure-ad#107]
bunyan is a logger that should only be used in the main application. Besides, all the debug statements are sent to bunyan's `info` level.
Following the [12factor recommendation on logs](http://12factor.net/logs), you should send debug statements directly to `stdout` or `stderr` and let the main application handle output channeling (file, database, alerts, notifications etc) itself.

**Comment by artparks** [comment]
Any progress on this? Bunyan has completely broken for me (due to [this](https://github.com/trentm/node-bunyan/issues/216) omnishambles). I don't understand why this module needs to pull in its own logging dependency at all and the sooner it's removed the better.

**Comment by brentschmaltz** [comment]
@artparks closing as a dup of : https://github.com/AzureAD/passport-azure-ad/issues/196
