### ISSUE TITLE
Who is responsible for OAuth 'state' persistence and verification?

### ISSUE THREAD

**Issue by silhouettes** [AzureAD/passport-azure-ad#111]
Looking through the code and dependencies, I can't find anywhere that the 'state' parameter is being persisted to the session, or verified after it is returned to us in the redirect URL.

Am I right in concluding that it is up to the consumer of this module to handle this? i.e. I need to do the following:

1. Generate state and persist to session
2. Pass the state to this module when the OAuth process starts
3. Retrieve the returned state from the params of the redirect URL
4. Verify the returned state against the state persisted in the session

If this is the case, it would be slightly different from what `passport-github` and `passport-windowslive` do, which is handle state persistence/verification for us by delegating it to the `passport-oauth2` module. If this is not the case, would you mind giving me a pointer to where this is happening, because I'm having trouble configuring it correctly?

**Comment by silhouettes** [comment]
Hi! Just following up on this, in case it has been forgotten. In case it helps, this is a useful resource: https://tools.ietf.org/html/rfc6749#section-10.12.

This is a fairly important security feature, so any investigation you do would be extremely helpful!

**Comment by lovemaths** [comment]
done
