### ISSUE TITLE
fix the example bugs

### ISSUE THREAD

**Issue by lovemaths** [AzureAD/passport-azure-ad#113]
There are a couple of issues:
1. the path of the corresponding strategy included is wrong in app.js
2. the config file needs update and correction, for the non-b2c strategies, I think we should use our own tenant, client id and client secret. The default ones won't work due to the following reasons:
(1) client secret provided in config file is invalid, so one cannot use the authorization code at all
(2) using the default identityMetadata in the config file can never yield a "email" field, which causes the example program to crash

**Comment by brandwe** [comment]
Yes the values in the config aren't useable. We assume the developer will do this and the config is an example. We  can replace with <insert here> values.

**Comment by polita** [comment]
Please open remaining samples issues in the samples repo.
