### ISSUE TITLE
Running examples fails with Cannot find module '../../lib/passport-azure-ad/index'

### ISSUE THREAD

**Issue by murdockcrc** [AzureAD/passport-azure-ad#135]
Repro steps:

1. Clone the repo
2. Adjust the config.js files with proper value
3. Run the server.js or app.js

I have tried this with _login-oidc_ and _server-oauth2_, they all fail with the same error. Seems like the ```require``` path is wrong?

**Comment by lovemaths** [comment]
yes the path is wrong, use '../../lib/index' instead
