### ISSUE TITLE
Bearer token and Microsoft graph access

### ISSUE THREAD

**Issue by kurtb** [AzureAD/passport-azure-ad#156]
The Microsoft Graph APIs appear to want you to set a 'resource' field when exchanging a code for an authorization token. https://graph.microsoft.io/en-us/docs/authorization/app_authorization.

The passport library does return the access token but without setting the resource field it doesn't have permissions to the graph API. Also the scope parameter doesn't seem to affect being able to get these permissions as well (should it for this API?).

Curious if updating the API to take in resource is the correct fix here?

**Comment by lovemaths** [comment]
@kurtb Now access_token is only used for userinfo endpoint. We won't support it in the upcoming release. It is a good thing to have, we might decide to add it in the future. Thank you for bringing it up!
