### ISSUE TITLE
Robustness work for OIDCStrategy

### ISSUE THREAD

**Issue by brandwe** [AzureAD/passport-azure-ad#157]
The id_token should be verified before the profile is loaded and handed back to the developer.

**Comment by dennisx5** [comment]
I suppose the failureRedirect should be used as to route to, when id_token is not present or validated to false. Currently at my returnUrl I only receive the errormessage "Error: ID Token not present in response" and can't navigate back to my app.

**Comment by jeffwilcox** [comment]
@dennisx5 thank you - I've been seeing that specific error message for a while and super confused when that has showed up in logs or error reports.
