### ISSUE TITLE
WsFedSaml.js hangs fetching signature using Xpath.js (on macOS)

### ISSUE THREAD

**Issue by seanhig** [AzureAD/passport-azure-ad#159]
Since upgrading to 2.0, my WSFED based AzureAD authentication kept hanging, and I traced it down to the double quotes at the end of this line:

const xpathExpression = '/*/*[local-name(.)="Signature" and namespace-uri(.)="http://www.w3.org/2000/09/xmldsig#""]';

(line 67: https://github.com/AzureAD/passport-azure-ad/blob/master/lib/wsfedsaml.js)

Note the two double quotes at the end of the expression constant.

It was hanging in the xmlCrypto.xpath function, but once I removed the 2nd quote, it worked fine again.

Forked it, changed to this:

const xpathExpression = '/*/*[local-name(.)="Signature" and namespace-uri(.)="http://www.w3.org/2000/09/xmldsig#"]';

(Seems like it is a typo, but it has been years since I did any xpath)

And now it works again.  Took some time to isolate the issue. Sort of head scratcher as to why something like this wouldn't be affecting everyone... hesitated to report it... but since the fix worked for me, I'm curious.  If this was actually the bug I must be the only person in the world using this :)

Running Node.js 6.3.1 on macOS Sierra Beta4, but I don't think any of that is relevant ;)

**Comment by polita** [comment]
Fixed in 2.0.1.
