### ISSUE TITLE
"Invalid signature" error resulting from always selecting first jwks_uri key

### ISSUE THREAD

**Issue by justaniles** [AzureAD/passport-azure-ad#160]
Commit #139 seems to have fixed a critical error that my team at Microsoft encountered yesterday.

AAD recently rolled out a new common key that resulted in two keys being returned for their [jwks_uri](https://login.microsoftonline.com/common/discovery/keys), instead of one. This raised a rather insidious error for us as we tried to track down why the rolling of AAD's new key caused our authentication to break (especially since we assumed that [Passport would automatically handle key rollovers](https://azure.microsoft.com/en-us/documentation/articles/active-directory-signing-key-rollover/#passport)).

While our team was able to patch the issue for the time-being, I just wanted to bring this to your team's attention, in case other people run into this same issue!

**Comment by dhodgin** [comment]
hitting the same issue today. all of a sudden using BearerStrategy I get
```
{"name":"AzureAD: Bearer Strategy","hostname":"Daniel-ASUS","pid":2496,"level":40,"msg":"An error was received validating the token invalid signature","time":"2016-08-22T18:39:49.759Z","v":0}
```
i get `Invalid token (invalid signature)` client side after successfully authenticating. I'm pretty sure it has to do with the emails i've been getting from Azure about:
```
On August 15, 2016, the Azure Active Directory (Azure AD) signing key will roll over. Your application(s) may experience downtime if it does not automatically handle this rollover. 
```
I have no idea what a signing key is. I just assumed it didn't affect me since we just use the clientId and tenant to authenticate and don't issue additional keys for our app.

but apparently it does matter... hugely... because no one in our app can authenticate using AD anymore and gets this error.

**Comment by lovemaths** [comment]
@dhodgin Are you using the BearerStrategy in the dev branch? I think we fixed this problem in the dev branch already.

**Comment by dhodgin** [comment]
I was using a commit from my own fork that had fixes for BearerStrategy that weren't merged at the time.

my version doesn't work
version 2.0.0 from npm install of the latest doesn't work either
and the latest commit from dev branch crashes our server as soon as i start it with `done is not a function` errors which was the errors I had fixed a few months ago that were merged into master but never added to dev branch.

there is no current state of the code that contains fixes for the key rollover and the done is not a function errors. this means there is virtually no one using the BearerStrategy in a working state anywhere most likely.

how can we get my fixes into the dev branch?
see: https://github.com/AzureAD/passport-azure-ad/pulls?q=is%3Apr+is%3Aclosed+author%3Adhodgin

those landed Pr's are all to master by mistake but i t looks like they were never added to dev. i don't know how you guys would want to get them in.

i tried to do a pr from master to dev but it adds tons of other commits and cant merge clearly.

i could recreate my pr's against dev instead but they are already on master

**Comment by lovemaths** [comment]
@dhodgin The problem might be the bug in Metadata.prototype.generateOidcPEM in metadata.js, where passport always chose the first key. We fixed the problem in dev as well.  

In line 186 of metadata.js
(https://github.com/AzureAD/passport-azure-ad/blob/master/lib/metadata.js)

185    // are we working on the right key?
186    if (!key.kid === kid) {
187      return false;
188    }

change line 186 to if (key.kid !== kid)

Please let me know if this solves your problem.

**Comment by lovemaths** [comment]
@dhodgin Please consider downloading the whole library from github and use the complete dev branch. We completely rewrote the BearerStrategy.js and fixed a bunch of bugs in dev branch, we tested it with samples as well. As long as the verify function matches the passReqToCallback in your config file, it should work well.

**Comment by dhodgin** [comment]
Ok do you think you will be blowing away the master branch woth dev when the time comes for a future release? I have 3 patches in master that are not in dev and the dev branch does not work at all with the BearerStrategy in it's current state. as soon as you try to use it you get done is not a function as a result of the passReqToCallback. i can resubmit those patches to dev but i don't know how you'll want to deal with the master and dev branches diverging in history

**Comment by dhodgin** [comment]
your comment
```
change line 186 to if (key.kid !== kid)
```
fixes the problem and i can login now. my version of the code had `!key.kid === kid`.

so it seems to work with that fix

should i open another issue to look into how to get my other 3 patches into dev? it's off topic for this issue but we should solve those problems

**Comment by dhodgin** [comment]
it looks like the dev branch works but you have to now pass `passReqToCallback : true` when setting up the passport.use call for the AD BearerStrategy. passReqToCallback used to be hardcoded to true before it was re-written. is this intended? should a bug be filed for this?

**Comment by lovemaths** [comment]
@dhodgin We already have the fix of your aadutils.js PR, and we will have the PR regarding the typo in soon. The bearerStrategy PR regarding _.extend is no longer applicable since now we have a different implementation in dev. 

I didn't realize the default passReqToCallback is true for bearerStrategy, will fix it soon. Thank you.

**Comment by dhodgin** [comment]
Thanks @lovemaths. I don't know if the default for passReqToCallback is supposed to be true. I only meant i used to be `true` passed to the passport BearerStrategy in the .call before the rewrite and was hardcoded. now, by not hardcoding it users will get a done is not a function error until they add `passReqToCallback: true` when using the strategy.

**Comment by lovemaths** [comment]
@dhodgin We will put your typo PR in the next release, thanks.
