### ISSUE TITLE
Comment when 'options.validateIssuer' is false / null is not correct

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/passport-azure-ad#163]
The comment (see below) suggests that issuer need not be validated when multiple idp's are used. This isn't true, we need work to support multiple idp's. That is a separate issue. For now, change the sentence "This is fine ..." to "Production environments should always validate the issuer. For multiple issuers custom code will be required."

// warn about validating the issuer
  if (!options.validateIssuer) {
    log.warn(`We are not validating the issuer.
      This is fine if you are expecting multiple organizations to connect to your app.
      Otherwise you should validate the issuer.`);
  }

**Comment by polita** [comment]
Already fixed.
