### ISSUE TITLE
By default redirect URL should be https.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/passport-azure-ad#164]
https://github.com/AzureAD/passport-azure-ad/pull/162/files#diff-dac9acad3c0a1da97f74286ae8c79470L154 

Allows http by default. We should fault on http and require a switch on options to be set.

**Comment by jeffwilcox** [comment]
Thanks. Happy to validate this one once a fix is available; we have deployed dev-test-prod that are all sitting behind SSL terminated app service instances, but for local dev we have a debug flag to allow debugging using HTTP + port 3000.

**Comment by polita** [comment]
Need an option to specify allowing http redirectUri
