### ISSUE TITLE
BearerStrategy initialization is asynchronous 

### ISSUE THREAD

**Issue by kayjtea** [AzureAD/passport-azure-ad#167]
When initializing metadata from URL, initialization is asynchronous. This leads to the server listening for HTTP requests before passport is fully ready to be used. In a situation where instances are spun up as needed, this leads to some web requests failing. Initialization should probably take a done callback as well as an error callback. Or maybe initialization should be synchronous. Have any of you run into this problem?

**Comment by kayjtea** [comment]
Oops I see the callback is passed err === null on success.

**Comment by kayjtea** [comment]
But callback isn't exposed by Strategy initialization.

**Comment by lovemaths** [comment]
@kayjtea This is issue #90 , we already fixed this problem in dev branch and we will put the fix into the next release. Thanks.

**Comment by lovemaths** [comment]
Shipped the fix in the most recent release (v2.0.1), closing the issue.
