### ISSUE TITLE
ResponseMode should be optional in OIDC requests 

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/passport-azure-ad#172]
https://github.com/AzureAD/passport-azure-ad/blob/master/lib/validator.js#L70
This code requires a responseMode, but responseMode is optional. It is not recommended to send it when it equals the default.

http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

**Comment by polita** [comment]
ResponseMode should support a 'default' or 'not set' value, which specifies that the responseMode shouldn't be sent and the app's registered responseMode is used.

**Comment by pkanher617** [comment]
This will be supported in `@azure/msal-node` and the future passport library. Closing for now, tracking in our backlog.
