### ISSUE TITLE
Profile name attributes are undefined

### ISSUE THREAD

**Issue by danielgranat** [AzureAD/passport-azure-ad#174]
This is probably not the right place for this since it looks like the server side thing.
When getting the profile back i get the following:
```
  displayName: 'Daniel Granatshtein',
  name: 
   { familyName: undefined,
     givenName: undefined,
     middleName: undefined },
```
The raw response contains only ```"name":"Daniel Granatshtein"```

Looking at the function makeProfileObject in oidcstrategy.js:
```
displayName: src.name,
    name: {
      familyName: src.family_name,
      givenName: src.given_name,
      middleName: src.middle_name,
    },
```
This is confusing, and requires me to break it down myself (unless i missed anything).

IMHO Ideally the names should have been send separately from the server, but as long as those are not send, the profile should not contain the name block, or it should break the raw.name in to the profile.name block.

What do you think? Have I missed anything?

**Comment by lovemaths** [comment]
@danielgranat We only collect the data in userinfo/id_token received from AAD, and pass them back to developers. We won't make any changes on the data itself, it is up to the user to decide how to interpret and use these data. Please consider adding custom code to fit your need. Thanks.
