### ISSUE TITLE
Select user instead of automatic redirect on authenticate

### ISSUE THREAD

**Issue by francescoinfante** [AzureAD/passport-azure-ad#175]
I'm testing this sample of the OIDC strategy:
https://github.com/Azure-Samples/active-directory-node-webapp-openidconnect

The problem that I have occurs when I login, logout and login again.
The second time I login it doesn't prompt me with a "select user" page but it immediately redirects me to `callbackURL`.

Basically I'm never able to change the user that login in the application for the first time without exiting the application.

IF I actually authenticate another user by manually calling `https://login.microsoftonline.com/{tenant}/oauth2/authorize?` with `prompt=login`
the next time I try to authenticate in my application I can choose among the two users as expected. But I can't reach this status within the application itself.

**Comment by lovemaths** [comment]
@francescoinfante change line 187 - 190 to:

app.get('/logout', function (req, res) {
  req.session.destroy(function(err) {
    req.logOut();
    res.redirect('https://login.microsoftonline.com/common/oauth2/logout?post_logout_redirect_uri=http://localhost:3000');
  });
});

The reason is that you still have a session with AAD, you need the additional code to destroy the session.
