### ISSUE TITLE
Error: Invalid signature

### ISSUE THREAD

**Issue by CharlotteSjothun** [AzureAD/passport-azure-ad#21]
There is trouble with the signature for users with a name that contains æ, ø or å.

In saml.js:

    // asynchronously process the samlResponse to create the user profile
    async.waterfall([
    // parse the samlResponse into a JavaScript object
    function(next){
      xml = new Buffer(samlResponse, 'base64').toString('ascii');

Because of .toString('ascii') "æ" becomes "C&" (which leads to "unexpected close tag" in sax.js), "ø" becomes "C8" and "å" becomes "C%" (which leads to a mismatch with the signature).

When we use .toString() it works fine, but I don't know if that's the most optimal solution.

    xml = new Buffer(samlResponse, 'base64').toString();

**Comment by brandwe** [comment]
This is very interesting. I need to remember why we originally locked this down to ASCII. Give me a few days to do some research? Meanwhile I assume you're doing this in your code with no issues so far?

**Comment by CharlotteSjothun** [comment]
It has been fixed in pull request #24 from flikka/ascii-to-utf8 :) So this can be closed
