### ISSUE TITLE
Unable to Authorize token for B2C Web API - Token is not Found

### ISSUE THREAD

**Issue by SamKosky** [AzureAD/passport-azure-ad#215]
Let me start off by saying that the overall concept of Azure AD B2C is great! However, I have been struggling to Authorize a bearer token for several days. One big issue is inconsistent and/or poor documentation. Even the standard B2C Nodejs web api app won't work due to conflicting configuration settings (identityMetadata set to common and validateIssuer = true). There are many other issues with the documentation, so I would test this thoroughly before deploying to the public.

I initially setup an ASP.NET web api, which worked locally, but not when deployed to an Ubuntu server. It seems as though there's an incompatibility with something in the Microsoft.Identity.Token and mono. I agree that I could've deployed this as an Azure web app or to a Windows Server VM, but I'm restricting to using linux VMs at this stage.

I then moved over to NodeJS, which seems like a better choice for a linux VM. Tried using the app provided in this repo and didn't work. Tried tweaking a few things here and there, and still nothing. These are the things that I've tried in order to get a web api to Authorize a token:

- Adjusted OIDC Bearer Strategy options. This is what I have now:
```
exports.creds = {
    clientID: '<clientid>',
    audience: '<clientid>',  // not sure whether this can be a client id or has to be your apps web uri. I've tried both.
    identityMetadata: 'https://login.microsoftonline.com/<tenantid>/v2.0/.well-known/openid-configuration', 
    issuer: 'https://login.microsoftonline.com/<tenantid>/v2.0/',  // again, i've tried with and without this option
    tenantName: '<tenantid>',    // tried with both id and name
    policyName: 'b2c_1_sign_upin',   // checked policy was created in lowercase
    validateIssuer: true,   // tried with both true and false
    loggingLevel: 'info', // valid values are 'info', 'warn', 'error'
    passReqToCallback: false
};
```
I have then tried cutting back as many options as possible when instantiating the bearer strategy, but doesn't make a difference. This is what the instantiation looks like:
```
var oidcStrategy = new OidcBearerStrategy(options,
    function(token, done) {
        log.warn('verifying the user');
        log.warn('token retrieved: ' + token);
        done(null, token.oid);
        // removed call to findById - I also think this is wrong as it uses token.sub, which isn't
        // implemented in B2C yet. The doco says to use token.oid instead
    }
);
```
However, this function is never called as it can never find the token.

- I then tried changing the creation of the route so I could inspect any errors or additional info returned from passport.authenticate:
```
server.get('/api', function(req, res, next) {
    passport.authenticate('oauth-bearer', function(err, tokenFound, info) {
        if (err) {
            log.error(err);
            return next(err);
        }
        if (!tokenFound) {
            return res.send('token: ' + tokenFound + ', info: ' + info);   // This is always the result
        }
        res.send('Successfully found token: ' + tokenFound);        
    })(req, res, next);
});
```
The response is always **"token: false, info: token is not found"**

In order to test all of this, I am using Postman, and simply inserting 'bearer + token' in the Authorization header. I generate my test tokens via the B2C policy, and have also checked what the token contains via calebb.net. Here is a sample token for your reference:
````
{
 typ: "JWT",
 alg: "RS256",
 kid: "IdTokenSigningKeyContainer.v2"
}.
{
 exp: 1473898726,
 nbf: 1473895126,
 ver: "1.0",
 iss: "https://login.microsoftonline.com/<tenantid>/v2.0/",
 sub: "Not supported currently. Use oid claim.",
 aud: "<clientid>",
 acr: "b2c_1_sign_upin",
 nonce: "defaultNonce",
 iat: 1473895126,
 auth_time: 1473895126,
 name: "my name",
 idp: "google.com",
 oid: "e9f818b9-bbae-4e76-b755-77a818blah"
}.
[signature]
````
Another bit of info that may come in handy is that the WWW-Authenticate header in the response I receive via Postman returns **"token is not found"**. In the documentation, it looks like it always returns **Bearer realm="Users"**.

I also tried deploying my web api to my ubuntu server just in case Azure had an issue with the web api calls not being secure. This also didn't make a difference.

I believe I have exhausted my options. I'd love to use AD B2C for authentication and authorization, but it's so frustrating getting anywhere at the moment!

**Comment by lovemaths** [comment]
@SamKosky Could you please try the latest version 2.0.3 and let me know if it works? The old version of B2C bearerStrategy contains a bug (wrong public key is loaded).  I don't see anything wrong in your code, I guess it is caused by the bug in the old version.

**Comment by SamKosky** [comment]
I was really hoping that would fix it, but still have the same issue. These are my dependencies:
```
    "assert-plus": "^1.0.0",
    "bunyan": "^1.8.1",
    "ejs": "^2.5.2",
    "ejs-locals": "^1.0.2",
    "express": "~4.9.0",
    "passport": "^0.3.2",
    "passport-azure-ad": "^2.0.3",
    "restify": "^4.1.1"
```

And this is what gets logged to the console:
```
{"name":"AzureAD: Bearer Strategy","hostname":"PCNAME","pid":11696,"level":30,"msg":"B2C: using policy b2c_1_sign_upin","time":"2016-09-15T06:47:41.536Z","v":0}
{"name":"AzureAD: Bearer Strategy","hostname":"PCNAME","pid":11696,"level":30,"msg":"Metadata url provided to Strategy was:  https://login.microsoftonline.com/<tenantid>/v2.0/.well-known/openid-configuration?p=b2c_1_sign_upin&x-client-SKU=passport-azure-ad&x-client-Ver=2.0.3","time":"2016-09-15T06:47:41.539Z","v":0}
{"name":"AzureAD: Metadata Parser","hostname":"PCNAME","pid":11696,"level":30,"msg":"Parsing JSON retreived from the endpoint","time":"2016-09-15T06:47:43.975Z","v":0}
{"name":"AzureAD: Metadata Parser","hostname":"PCNAME","pid":11696,"level":30,"msg":"Request to update the Open ID Connect Metadata","time":"2016-09-15T06:47:43.976Z","v":0}
{"name":"AzureAD: Metadata Parser","hostname":"PCNAME","pid":11696,"level":30,"msg":"Algorithm retrieved was:  [ 'RS256' ]","time":"2016-09-15T06:47:43.980Z","v":0}
{"name":"AzureAD: Metadata Parser","hostname":"PCNAME","pid":11696,"level":30,"msg":"Issuer we are using is:  https://login.microsoftonline.com/<tenantid>/v2.0/","time":"2016-09-15T06:47:43.980Z","v":0}
{"name":"AzureAD: Metadata Parser","hostname":"PCNAME","pid":11696,"level":30,"msg":"Key Endpoint we will use is:  https://login.microsoftonline.com/<tenantid>/discovery/v2.0/keys?p=b2c_1_sign_upin","time":"2016-09-15T06:47:43.981Z","v":0}
{"name":"AzureAD: Metadata Parser","hostname":"PCNAME","pid":11696,"level":30,"msg":"Authentication endpoint we will use is:  https://login.microsoftonline.com/<tenantid>/oauth2/v2.0/authorize?p=b2c_1_sign_upin","time":"2016-09-15T06:47:43.982Z","v":0}
{"name":"AzureAD: Metadata Parser","hostname":"PCNAME","pid":11696,"level":30,"msg":"Token endpoint we will use is:  https://login.microsoftonline.com/<tenantid>/oauth2/v2.0/token?p=b2c_1_sign_upin","time":"2016-09-15T06:47:43.983Z","v":0}
{"name":"AzureAD: Metadata Parser","hostname":"PCNAME","pid":11696,"level":30,"msg":"User info endpoint we will use is:  undefined","time":"2016-09-15T06:47:43.984Z","v":0}
{"name":"AzureAD: Metadata Parser","hostname":"PCNAME","pid":11696,"level":30,"msg":"The logout endpoint we will use is:  https://login.microsoftonline.com/<tenantid>/oauth2/v2.0/logout?p=b2c_1_sign_upin","time":"2016-09-15T06:47:43.985Z","v":0}
```
Not sure whether the User Info endpoint is an issue or not, but i'm assuming this is undefined as we are supposed to use the Graph API to retrieve this sort of info.

**Comment by lovemaths** [comment]
@SamKosky All these logs are correct behavior since we load all the information in metadata first. It seems after loading the metadata, passport failed to find the token in header. Did you use 'Bearer' (not 'bearer') in your header? The authorization field in header should be like:

```
Authorization: Bearer <your_id_token>
```

**Comment by SamKosky** [comment]
Wow. So I'm going to say I made a rookie mistake and used 'bearer' instead of 'Bearer' in Postman. It's always something so trivial!

Thanks so much for your help!
