### ISSUE TITLE
Missing email claim for B2C

### ISSUE THREAD

**Issue by tejak1** [AzureAD/passport-azure-ad#218]
There is no way to mention the name of a custom sign-in policy name in the '/examples/login-oidc-b2c/client_config_b2c.js' file, unlike the examples/server-oauth2-b2c/server_config.js file (policyName). I am unable to get proper claims post sign-in (especially email) for my Node app with the current configuration scope.

**Comment by lovemaths** [comment]
Passport has a bug returning the email claim. We are working on the fix and we will release as soon as we can with a fix to B2C. Thanks.

**Comment by tejak1** [comment]
Thank you.

**Comment by lovemaths** [comment]
@tejak1 By the way, OIDC figures out the policy by itself, we don't provide policy names in the config file. User just needs to make sure they add the policy name in the route they want to authenticate, please have a look at the routes in 'views/index.ejs'. I changed the title of this issue to 'missing email claim for B2C'.

**Comment by tejak1** [comment]
Yes, I have the policy name updated in the routes. I didn't know if the 'no email' found' error was thrown due to not mentioning the policy name in the configuration file also. Thanks for the clarification.
