### ISSUE TITLE
B2C sample breaks with 2.0.3

### ISSUE THREAD

**Issue by SteenMolberg** [AzureAD/passport-azure-ad#219]
Hi,

I have based a new projekt on the principles from this sample on AzureB2C and Node...
https://github.com/AzureADQuickStarts/B2C-WebApp-OpenIDConnect-NodeJS

But after upgrading the passport-azure-ad to 2.0.3 I get this error when redirected after login:
"a key with kid %s cannot be found"

I had to copy the 2.0.0 module from the sample to get it to work again after a lot of debugging and troubleshooting. I know there are some security issues with that version, but at long as I'm developing at least I can work.

Can you help me out how I can get rid of this error? Thank you..

**Comment by GreenToast** [comment]
+1

My example works with 2.0.0, but ^2.0.1 breaks it. Seems to be something in the token-validation.

**Comment by lovemaths** [comment]
We are working on the issue and we will release as soon as we can with a fix to B2C. Thanks.

**Comment by SteenMolberg** [comment]
That's great to hear. I hope it's not to far away.

**Comment by starlightyear** [comment]
Waitinggggggggggg

**Comment by lovemaths** [comment]
@GreenToast  @SteenMolberg  We published a new version 3.0.0 which fixed the B2C issues. It has some small breaking changes, please have a look at the changelog. The B2C sample using 3.0.0 is here: https://github.com/AzureADQuickStarts/B2C-WebApp-OpenIDConnect-NodeJS

Thank you for the waiting!

**Comment by SteenMolberg** [comment]
Thank you @lovemaths I will check it out during the weekend:)
