### ISSUE TITLE
identity SAML callback not called

### ISSUE THREAD

**Issue by fpereira1** [AzureAD/passport-azure-ad#22]
There seems to be an issue with viewing a `/identity` route as in the example for SAML authentication. [examples/login-saml/app.js#L193](https://github.com/AzureAD/passport-azure-ad/blob/master/examples/login-saml/app.js#L193)

Where the first load of `/identity` works fine, but the next won't, as the callback is never called when it does not match the condition anymore `this.federationMetadata === null` see in [saml.js#L104-L111](https://github.com/AzureAD/passport-azure-ad/blob/master/lib/passport-azure-ad/saml.js#L104-L111)

Happy to submit a pull request with the following fix, if agreed to be an issue.

```javascript
if(this.federationMetadata === null) {
    templates.compile('federationmetadata.template.xml', params, function(err, data) {
      if(err === null) {
        self.federationMetadata = data;
      }
      callback(err, data);
    });
} else {
    callback(null, this.federationMetadata);
}
```

**Comment by brandwe** [comment]
Awesome fix. Definitely submit a pull request to get credit for the find!
