### ISSUE TITLE
[B2C] signUp link sometimes signs in automatically

### ISSUE THREAD

**Issue by starlightyear** [AzureAD/passport-azure-ad#223]
Hi,
I am a beginner with Azure and OAuth in general.
My signin and signup links are finally working. Suppose I signup for the first time and get logged in.
Now i want to signup again as another user. So when I click on signup, it automatically signs me in as previous user.
Can you tell me what needs to be changed.

Also, during signup, how can I remove the email verification using verification code? Can I add my own custom fields like selectbox?

**Comment by lovemaths** [comment]
@starlightyear

(1)  It seems to me if the browser already has a session with AAD, then AAD won't allow you to sign up. Either you use a different browser to sign up, or you can destroy the session with AAD first by logging out with the following code and then sign up.

```
// replace `<tenant_name>` and `<sign_in_policy_name>`  in `destroySessionUrl`

var destroySessionUrl =
https://login.microsoftonline.com/<tenant_name>.onmicrosoft.com/oauth2/v2.0/logout' +
  '?p=<sign_in_policy_name>' +
  '&post_logout_redirect_uri=http://localhost:3000';

app.get('/logout', function(req, res){
  req.session.destroy(function(err) {
    req.logOut();
    res.redirect(destroySessionUrl);
  });
});
```

(2)  You can go to the setting of your sign up policy, click 'Edit policy'. On that page, there is an option called 'Page UI customization'. I don't know much about this, please refer to the following page:
https://azure.microsoft.com/en-us/documentation/articles/active-directory-b2c-reference-ui-customization/
