### ISSUE TITLE
QUESTION: AAD OAuth2 `the v2.0 endpoint` support? So we can use one app to support MSA account(like xxx@live.com) + OrgId account(like xxx@microsoft.com)?

### ISSUE THREAD

**Issue by Huan9** [AzureAD/passport-azure-ad#226]
https://azure.microsoft.com/en-us/documentation/articles/active-directory-appmodel-v2-overview/ 
=> New OAuth2 V2.0 endpoint has been announced. 
1. Do we have AAD OAUTH2 V2.0 endpoint support in OIDCStrategy? 
2.If not, what is the plan to support it?
3. If so, any examples? The main problem I have is the `identityMetadata` available online : https://login.microsoftonline.com/common/.well-known/openid-configuration =>  does not have the new endpoint, do you guys know how we can use the new endpoints?

OR

What is your suggestion on support both MSA account and OrgId account?

**Comment by lovemaths** [comment]
@Huan9 The identityMetadata for v2 endpoint is like:
https://login.microsoftonline.com/<tenant_name>.onmicrosoft.com/v2.0/.well-known/openid-configuration

or 

https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration

**Comment by Huan9** [comment]
@lovemaths Thank you, that endpoint did work like a charm. Now I have another problem:
I use the `code` to go through the `Authorization Code Flow`. But for some reason I did not get any `access_token` or `refresh_token`, see below pic, any suggestion? Thanks!

![screen shot 2016-10-07 at 2 30 39 pm](https://cloud.githubusercontent.com/assets/14083050/19206150/c0c8de8c-8c9b-11e6-917a-244c731d7d39.png)

**Comment by lovemaths** [comment]
@Huan9 in config.js, use `['offline_access', 'https://graph.microsoft.com/mail.read']` as the `scope` value, and in app.js where you initialize the strategy, make sure you have `scope` in the option, for example:

```
passport.use(new OIDCStrategy({
  scope: config.creds.scope,
  ...
```

The scope `offline_access` is used to get refresh_token, and the scope `'https://graph.microsoft.com/mail.read'` is used to get access_token. Hopefully this will work for you.
