### ISSUE TITLE
The access_code I get cannot using OIDC strategy seems like is not a valid JWT bearer token, use it to make call to https://graph.windows.net/me?api-version=1.6 or https://management.azure.com/subscriptions?api-version=2015-01-01 does not work

### ISSUE THREAD

**Issue by Huan9** [AzureAD/passport-azure-ad#228]
I am blocked now, any pointers or suggestion will be more than welcomed!
Here is my config and I can get the access_token, refresh_token and id_token. 
But when I try to use Acces_code to query aginst the GET https://management.azure.com/subscriptions?api-version=2015-01-01 endpoint, I got error `401 Unauthorized InvalidAuthenticationToken`. The access_token does not look like a JWT Bearer token, I try to decode it but cannot.
 
But the `access_code` and `refresh_code` seems like valid ones as I can make a call to get a new `access_code`
![token_refresh](https://cloud.githubusercontent.com/assets/14083050/19248614/0c51dd58-8ee6-11e6-8e75-07490eadafee.png)

Blow is my config in case you want to take a look. 
var options = {
    callbackURL: 'http://localhost:8080/auth/aad/callback',
    realm: null,
    clientID: '104393f4-339b-4a77-be3d-8219f3a71a4e',
    clientSecret: "{ping me if you need this to repro}",
    oidcIssuer: null,
    identityMetadata: 'https://login.microsoftonline.com/common/.well-known/openid-configuration',
    scope: ['email', 'profile'],
    skipUserProfile: true,
    responseType: 'id_token code',
    responseMode: 'form_post',//'query',
    validateIssuer: false,
    passReqToCallback: true,
    loggingLevel: 'info',
    sessionKey: 'aadoidc'
  };

**Comment by lovemaths** [comment]
@Huan9 The access_token is for token endpoint only, it is not intended for graph api. When do you need this feature?

**Comment by Huan9** [comment]
passing below line tot he config fix the issue. resourceURL:'https://management.core.windows.net/' 

Thanks!
