### ISSUE TITLE
Support client_asserton for OIDC auth flow

### ISSUE THREAD

**Issue by Huan9** [AzureAD/passport-azure-ad#231]
We are using microsoft first party app as our AAD app to do auth. For all the first party app, we cannot use client_key to get access token, we are forced to use client assertion to get access tokens from Azure AD.  => without support for client_assertion, our subscription linking scenario will get blocked.

More detail has been described here:

https://azure.microsoft.com/en-us/documentation/articles/guidance-multitenant-identity-client-assertion/

So basically, it will be ideal, if we can pass in our private key in the config and the library can help to generate the singed JWT client_assertion when doing the token exchange process.

P.S. Search `client_assertion` in below blogs, I think it help to understand how the flow works:
http://www.dushyantgill.com/blog/2015/05/23/developers-guide-to-auth-with-azure-resource-manager-api/

http://www.andrewconnell.com/blog/user-app-app-only-permissions-client-credentials-grant-flow-in-azure-ad-office-365-apis

**Comment by Huan9** [comment]
@lovemaths Thank you for the help for the other 3 feature requests. Hope you can help with this as well!

**Comment by lovemaths** [comment]
@Huan9 We added this feature in release 3.0.4.
