### ISSUE TITLE
End_to_end_test showing up in test folder

### ISSUE THREAD

**Issue by stuartlong** [AzureAD/passport-azure-ad#248]
There is an "End_to_end_test" folder showing up under passport-azure-ad/test/ whenever I do an npm install for 3.0.2. I can't find a trace of it in the source code and it's causing me deployment issues on Windows because of  path too long issues (it's nesting it's node_module even though I'm on npm version 3.7.5).

On a related note, why are any of the tests included in the npm package in the first place?

**Comment by lovemaths** [comment]
@stuartlong This is weird, I didn't have that folder in my master branch when I published it. I will do a new release tomorrow. Thanks for letting me know.
