### ISSUE TITLE
v1.4.8 - using WsfedStrategy for auth supporting multiple tenants results in error

### ISSUE THREAD

**Issue by gbockus** [AzureAD/passport-azure-ad#250]
When authenticating using the Wsfed Strategy I always get the following error
```
Issuer is invalid. Expected: https://sts.windows.net/{tenantid}/, Received in token: https://sts.windows.net/0262da8d-xxxx-xxx-xxxx-xxxxxxxxxxxxx/
```
(note I replaced most of the tenantId in the message with x's).

Looking through the release notes I found the section talking about if you have to support multiple tenants then the validateIssuer option should be set the false.  

> If you are a multi-tenant app and need to go against the common endpoint, you must set validateIssuer to false. Be aware that the issuer field of the token will not be validated and all issuers will be accepted.

Looking though the code it appears support for that option was never added to the wsfed strategy.  We are using the common endpoint for identity metadata:
"https://login.windows.net/common/federationmetadata/2007-06/federationmetadata.xml"

There a pretty simple fix to add a check for options.validateIssuer to the wsfedsaml.js
```
      if (self.options.validateIssuer && !(self.options.metadata.metatdata.EntityDescriptor['$'].entityID === profile.issuer))
        return callback(new Error(`Issuer is invalid. Expected: ${self.options.metadata.metatdata.EntityDescriptor['$'].entityID}, Received in token: ${profile.issuer}`));
```

Is this the right approach for fixing the issue,  or is there a better option for me using one of the new strategies? 

Thanks

**Comment by lovemaths** [comment]
@gbockus Yes, this can fix the issue. I will fix it and do a release in the next two weeks. Thanks!

**Comment by gbockus** [comment]
Great!  Thanks for the quick response.

**Comment by gbockus** [comment]
HI @lovemaths Touching base on this one...Any guess on when it will be released? Thanks

**Comment by lovemaths** [comment]
@gbockus We will fix the bug and do a release sometime in January. Sorry for the delay.

**Comment by lovemaths** [comment]
@gbockus We are unlikely to do more official releases on release1x due to various of reasons. Please fork the library and apply the change you proposed. If you are using Azure Active Directory, then I think you can switch to oidcStrategy, the link to the sample using oidcStrategy is here: https://github.com/AzureAD/passport-azure-ad#71-samples-for-openid-connect-strategy
