### ISSUE TITLE
Multiple Audiences with Bearer Strategy

### ISSUE THREAD

**Issue by bondseid** [AzureAD/passport-azure-ad#251]
Hello,

We have token coming in from multiple resource endpoints and were protecting our server api with passport-azure-ad. Because of this we need to be able to verify against multiple audiences. 

Our config:

 identityMetadata: "https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration",
    clientID: "clientID",
    validateIssuer: false,
    passReqToCallback: false,
    allowMultiAudiencesInToken: true,
    audience: ["clientId", "https://graph.windows.net"],
    loggingLevel: "error"

From the readme i understood that i am able to set an array of strings for the audience parameter. When i do this however and test my token i get the following 401 response:

data: "options.audience is missing in jsonWebToken.verify"
headers: (c)
status: 401
statusText: "Unauthorized"

Am i missing something in my config?

**Comment by lovemaths** [comment]
@bondseid This is a documentation bug. 'audience' in the configuration has to be a string, otherwise bearerStrategy won't recognize it and it issues an "options.audience is missing in jsonWebToken.verify" error message. We will add this feature in the future.

**Comment by lovemaths** [comment]
Delivered in 3.0.4

**Comment by lovemaths** [comment]
@bondseid We already added this feature in the new release 3.0.4
