### ISSUE TITLE
For OIDCStrategy with Azure B2C it appears that the wrong claim is used for policy veirfication

### ISSUE THREAD

**Issue by maxrydkin** [AzureAD/passport-azure-ad#253]
For my Azue AD B2C the claims returned look like  this:
```
{
  "exp": 1479411870,
  "nbf": 1479408270,
  "ver": "1.0",
  "iss": "https://login.microsoftonline.com/<snip>/v2.0/",
  "sub": "<snip>",
  "aud": "<snip>",
  "nonce": "<snip>",
  "iat": 1479408270,
  "auth_time": 1479408270,
  "tfp": "B2C_1_signin",
  "c_hash": "<snip>"
}
```

The code in oidcstrategy.js#L844 checks the claim 'acr' not 'tfp' so validation fails

```
// For B2C, check the policy
    if (self._options.isB2C) {
      if (!jwtClaims.acr || !CONSTANTS.POLICY_REGEX.test(jwtClaims.acr))
        return next(new Error('In _validateResponse: invalid B2C policy in id_token'));

      if (params.policy !== jwtClaims.acr)
        return next(new Error("In _validateResponse: acr in id_token does not match the policy used"));
    }
```
In addition the check is case sensitive, but params.policy had been converted to lower case so that also fails

These issues make this sample broken https://github.com/AzureADQuickStarts/B2C-WebApp-OpenIDConnect-NodeJS

**Comment by lovemaths** [comment]
@maxrydkin This token doesn't seem to be a B2C token to me. What is the 'sub' claim in your token? The 'sub' claim is always "Not supported currently. Use oid claim." for B2C token.

**Comment by maxrydkin** [comment]
@lovemaths I guess it is configurable now?
<img width="285" alt="screen shot 2016-11-17 at 5 59 32 pm" src="https://cloud.githubusercontent.com/assets/2838425/20411462/995ded50-acef-11e6-96be-d78858656334.png">

So maybe its fine, I just need to configure the policy more for the ample to work.

**Comment by lovemaths** [comment]
@maxrydkin Yes, it seems it is configurable now. I will add the support in the future release. Please use 'acr' and let me know if everything works as expected. Thanks!

**Comment by maxrydkin** [comment]
@lovemaths, yes it seems to work if I change both the iss="acr" and sub="Not Supported", maybe the docs on the sample need to be updated for now?
