### ISSUE TITLE
No @types/passport-azure-ad

### ISSUE THREAD

**Issue by admeister** [AzureAD/passport-azure-ad#259]
I'm using TypeScript 2 and trying to use 'passport-azure-ad' package. When I put:

`import { BearerStrategy } from 'passport-azure-ad';`

tsc is reporting:

`error TS2688: Cannot find type definition file for 'passport-azure-ad'.`

I've tried

`npm i --save-dev @types/passport-azure-ad`

but the package cannot be found. Does anyone know when this will be able, or what the work around is until then?

**Comment by polita** [comment]
@admeister Unfortunately, we don't have a type definition for passport-azure-ad. There's one for passport, but we haven't had the chance to create one for passport-azure-ad. You can create one yourself, or you can proceed using passport-azure-ad in your code without referencing the type in your tsconfig.
