### ISSUE TITLE
prompt,domain_hint and login_hint are missing in the query params sent to endpoint

### ISSUE THREAD

**Issue by shakthi1231** [AzureAD/passport-azure-ad#261]
Every time we use this module to do Oauth, user is redirected to a selection page where he gets to choose his personal or work account. To avoid this additional step we can log the user in by setting query parameterx domain_hint(to either ''/organizations'' or "/consumers") and passing in a proper login_hint(email or username). By doing so user is automatically logged in from the second time and this avoids an additional step.Even "prompt" is widely used in most business use cases to reauthenticate user everytime. As these are configurable, I think it would be beneficial for different apps using this module by easing their login process. Moreover various modules like passport-azure-oauth support these params

**Comment by lovemaths** [comment]
Delivered in 3.0.4
