### ISSUE TITLE
OIDC authentication fails when oauth token_type is 'bearer' and not 'Bearer'

### ISSUE THREAD

**Issue by lindblad** [AzureAD/passport-azure-ad#264]
Got a problem for OIDC strategy on line 1030 in oidcstrategy.js
    // token_type must be 'Bearer'
    if (items.token_type !== 'Bearer') {
      log.info('token_type received is: ', items.token_type);
      return next(new Error(`In _authCodeFlowHandler: token_type received is not 'Bearer'`));
    }
Our AD returns 'bearer' token_type, not 'Bearer'. Is it possible to change the check to
if (items.token_type.toLowerCase() !== 'bearer') {
?

**Comment by lovemaths** [comment]
@lindblad Yes we can do that in the next release. I will make a PR for it.

**Comment by lovemaths** [comment]
Delivered in 3.0.4
