### ISSUE TITLE
Warn that cookie-parser, body-parser and express-session are required

### ISSUE THREAD

**Issue by joaomoreno** [AzureAD/passport-azure-ad#27]
It took me a while to find out that [expressjs/express-session](https://github.com/expressjs/express-session), [expressjs/cookie-parser](https://github.com/expressjs/body-parser) and [expressjs/body-parser](https://github.com/expressjs/body-parser) are required by this middleware. It's very hard to detect this, there's no error message at all.

Additionally, your samples should be updated to this:

```javascript
var cookieParser = require('cookie-parser');
var expressSession = require('express-session');
var bodyParser = require('body-parser');

// ...

app.use(cookieParser());
app.use(expressSession({ secret: 'keyboard cat', resave: true, saveUninitialized: false }));
app.use(bodyParser.urlencoded({ extended : true }));
```

**Comment by joaomoreno** [comment]
Created #28

**Comment by OwenBrotherwood** [comment]
@joaomoreno why did you not include the code above in your Pull Request?

**Comment by joaomoreno** [comment]
Plenty busy.
