### ISSUE TITLE
Reducing complexity for Single sign on

### ISSUE THREAD

**Issue by tvvignesh** [AzureAD/passport-azure-ad#273]
Hi. First of all, good work with the library.

I am facing an issue and I asked for solutions here: http://stackoverflow.com/questions/41279659/azure-active-directory-authentication-v2-0-for-web-mobile-apps

But, copying the same here as well:

I am trying to implement an **Azure AD authentication system (v2.0 using Single Sign On)** for a product in my organization and I have been able to do it except for 1 issue.

To understand the issue, here is the flow:

1) User visits the web app, types his email id and presses sign in with Organizational account

2) Now, the email id is used to get the domain (xyz@example.com means the user's domain is example.com) and I see the domain specific AD setting stored in our database which has been given to us by the admin of the organization (since this is not an on premise or client specific app. It is cloud app having single database, code and info for all companies)

3) Now, for authentication, it redirects to Office 365 website and asks for email id and password if not logged in.

4) Now, when we type in the email id in step 3, it takes us to a Single Sign On page asking user id (email id) and password.

5) On successful authentication, it sends oid and basic user info to the web app finally and we can thus use it to login the user using AD

Now, the issue:

From the above steps, we are taking email ID input from the user thrice (steps 1,3,4) and the same email ID is given in all 3 steps for user ID which leads to unnecessary complexity for the user in using a single sign on. How can this be avoided?

I thought of passing email ID as parameters after step 1 so that that can be used to autofill the field, but I am not sure if the applications (Office 365, Single Sign On page of respective organization) support it.

Note:

1) All these steps are followed by a new user signing up to our application from a foreign organization

2) Our application is on cloud and has a single database and codebase and hence we dont have any client specific info but map it with domain like domainName->tenantId

3) We are using NodeJS, Passport Azure AD (https://github.com/AzureAD/passport-azure-ad) and we are using **v2 common endpoint configuration** for this.

Any help is appreciated.

**Comment by lovemaths** [comment]
@tvvignesh You can try 'login_hint' to autofill the username field, and 'domain_hint' to specify the domain. For instance, the following code will redirect the user to 'live.com' login page directly, with username 'xxx.example.com' autofilled. This feature is in 'dev' branch, we haven't published it yet. Hopefully this will help.

```
 passport.authenticate('strategy_name',  { 'login_hint': 'xxx.example.com', 'domain_hint': 'live.com' })
```

**Comment by tvvignesh** [comment]
@lovemaths: Great to hear that such feature is on the lines of implementation in the future. Will try it out.

Any idea on when we can expect this feature in the master branch?

**Comment by lovemaths** [comment]
@tvvignesh We don't have a plan yet. I will let you know once we release it. Thanks.

**Comment by lovemaths** [comment]
@tvvignesh We did the release today. Please try it out. Your case seems more complicated, so I don't know how AAD interprets and responds to the login_hint and domain_hint parameters passport-azure-ad sends. Hopefully it will work for you.

**Comment by tvvignesh** [comment]
@lovemaths : Tried the new version with the parameters. Now, its like a boon. One step out of the 3 steps for email id is avoided. The remaining 2 cannot be avoided unless the person who is designing the SSO page (respective organization) allows autofilling of fields. So, the issue is settled! 

Cheers :+1:
