### ISSUE TITLE
Allow setting a custom cache for oidc startegy

### ISSUE THREAD

**Issue by omerlh** [AzureAD/passport-azure-ad#274]
Hey,
The OIDC strategy using a cache to validate the nonce and state parameters, and the default cache is 'memory'. Now, if I got multiple instances of my server, then it is possible that the authentication callback will be called on a different server than the one issue the request, resulting in an invalid request - because the cache is per instance. I would like to be able to pass the cache on the option to the strategy, and then I will be to use Redis cache or any other cache implementation. I can create a PR, but I would like to make sure this is a real issue, and not something I missed.

**Comment by lovemaths** [comment]
@omerlh The nonce, state etc are stored in session (controlled by express-session middleware), not memory. The following sample shows how to use express-session with MongoDB session store.  https://github.com/AzureADQuickStarts/WebApp-OpenIDConnect-NodeJS/blob/master/app.js#L153

**Comment by omerlh** [comment]
Yes, that what I was thinking. I was probably confused because of the cache create and used in this class. 
Thanks!
