### ISSUE TITLE
Semi-Dynamic redirectUri for passport-azure-ad

### ISSUE THREAD

**Issue by tvvignesh** [AzureAD/passport-azure-ad#278]
My use case is similar to what is mentioned here: https://github.com/jaredhanson/passport-facebook/issues/2

I have a working authentication system on my website (using passport-azure-ad) and I am basically using cordova inappbrowser to reuse the same authentication system for doing authentication from cordova app (Single Sign On).

Everything works fine except for the fact that this library does not allow me to specify dynamic urls. 
I want the plugin to be able to allow me to specify url like urn:ietf:wg:oauth:2.0:oob if authenticating from app but https://www.mywebsite.com/return if I am doing it from my website.

I want to pass the redirect Uri during passport.authenticate (with different redirect Uri for different sources) but the way it works now, it takes the redirectUri during initialization and thus this cannot be changed during authentication.

Right now, I am planning to use some hacks to solve this but better if this can be solved.

Cheers :-)

**Comment by tvvignesh** [comment]
You can also look at this link: https://developers.google.com/api-client-library/python/auth/installed-app to get a context of what I am talking about.

**Comment by Walk4Muscle** [comment]
`passport-azure-ad` is used in `node.js` service application. Have you tried [azure-activedirectory-library-for-js](https://github.com/AzureAD/azure-activedirectory-library-for-js) in your Cordova app?

**Comment by tvvignesh** [comment]
@Walk4Muscle : hi there. I am using it in node.js application and have it working properly and now, I am loading it in a cordova inappbrowser. 

So, this essentially works as a website within an app and redirects me back to the website after authentication. Now, I have to listen for the page load event by the cordova inappbrowser, read the token from local storage and close the browser if successful.

This method works but is hackish. I am kind of doing self XSS to make this work. To understand, I am giving you sort of a sample code.

       var authWindow = cordova.InAppBrowser.open('https://example.com/auth/openid?tenantId=xyz.onmicrosoft.com', '_blank', 'location=no,toolbar=no,clearsessioncache=yes,zoom=yes,hardwareback=no');

        var scriptInjection = 'function getToken(){return localStorage.getItem(\'jwttoken\');}getToken();';
        var executeScriptCallBack = function(params){
          if(params[0]){
            var token = params[0]; //getting return value of the function from the injected script
            saveToken(params[0]); //function for saving token to the local storage of the app
            authWindow.close(); //closing the browser window

            $http.get('https://example.com/api/loaduserinfo').success(function(response, status) {

              saveUser(response); //saving response as user information
              $scope.user = response;

              loginProcess(response,token); //logging in the user
            }).error(function(error){
              showToast('OOPS! An error occured in loading information!');
              return;
            });

**Comment by tvvignesh** [comment]
So, the solution for this which I guess would be allowing the redirectUrl to be set while doing the authenticate rather than during initial config.

I may be wrong here. So, please have your own judgement while thinking about this.

**Comment by lovemaths** [comment]
@tvvignesh 'state' parameter is usually used to remember a url before authentication, and retrieve after authentication. For example,
```
  app.get('/login', passport.authenticate('azuread-openidconnect', { state : 'url_you_want_to_remember' }));

  app.post('/redirectUrl', passport.authenticate('azuread-openidconnect'), function(req, res, next) {
    // retrieve the remembered url
    var url_remembered = req.body.state;
    // redirect to the url remembered
    res.redirect(url_remembered);
  });
``` 
Will this fit your need?

**Comment by tvvignesh** [comment]
@lovemaths : Perfect! Sorry for bothering you all. Did not think that state parameter can be used in such ways. My bad.
