### ISSUE TITLE
Invalid signature when using graph.microsoft.com as an audience

### ISSUE THREAD

**Issue by raiss** [AzureAD/passport-azure-ad#280]
### issue

I try to authenticate a request which has a token, generated for the resource graph.microsoft.com.

`acquireTokenAsync("https://graph.microsoft.com", "xxxxx....xxxx")` 

I can successfully use this token to consume the graph.microsoft.com resources e.g.
`https://graph.microsoft.com/v1.0/users/{userID}/photo/$value` 

However, when I want to use the same token in my Node.js app (using passport-azure-ad), I get the invalid signature. I use the OIDCBearerStrategy with the following options

```javascript
{
  identityMetadata: 'https://login.microsoftonline.com/7{tenantID}/v2.0/.well-known/openid-configuration',
  clientID: '{clientID}',
  validateIssuer: true,
  issuer: 'https://sts.windows.net/{tenantID}/',
  audience: 'https://graph.microsoft.com',
}
```

err: 
`[2017-02-09T23:30:34.285Z]  INFO: AzureAD: Bearer Strategy/46985 on My-MacBook-Pro.local: authentication failed due to: invalid signature`

Is there anything extra that needs to be enabled to recognise such tokens.

### More info

If I change the resource to **graph.windows.net** (instead of graph.microsoft.com) I can **successfully** use both graph api (graph.windows.net) and my backend api (with the same options except the audience which is graph.windows.net)

lib versions:
- passport: "0.3.2"
- passport-azure-ad: "3.0.4"

**Comment by lovemaths** [comment]
@raiss I can reproduce this issue. It seems to me the access_token is not signed using the key provided by the metadata, which causes the signature verification failure. Still investigating.

**Comment by lovemaths** [comment]
@raiss The access token for https://graph.microsoft.com can only be verified by graph.microsoft.com, so this library cannot be used for that kind of access token. Sorry about that. Closing the issue.
