### ISSUE TITLE
OIDC strategy requires session support. Did you forget to use session middleware such as express-session?

### ISSUE THREAD

**Issue by makromat** [AzureAD/passport-azure-ad#284]
Hi there.

I got error "OIDC strategy requires session support. Did you forget to use session middleware such as express-session? "

but my express-session is installed well. 

    const express          = require('express')
    const https            = require('https')
    const http             = require('http')
    const ECT              = require('ect')
    const multer           = require('multer')
    const upload           = multer({ dest: __dirname + '../public/uploads/'})
    const bodyParser       = require('body-parser')
    const session          = require('express-session')
    const passport         = require('passport')
    const redis            = require('redis')
    const RedisStore       = require('connect-redis')(session)
    const morgan           = require('morgan')
    const fs               = require('fs')
    const lusca            = require('lusca')
    const url              = require('url')
    const expressValidator = require('express-validator')
    const compression      = require('compression')
    const _                = require('lodash')
    const util             = require('util')
    const env              = process.env.NODE_ENV || 'production'; // development or production => changes config and secrets settings
    const secrets          = require('./config/secrets')[env];
    const azureconf        = require('./config/azure');
    const app              = express()
    const ectRenderer      = ECT({ watch: true, root: __dirname + '/views', ext : '.ect', gzip: true });
    const docDBclient      = new DocumentClient(secrets.documentDB.endpoint, {"masterKey": secrets.documentDB.authKey});
    //const parser           = require('xml2json')
    const OIDCStrategy     = require('passport-azure-ad').OIDCStrategy;
    const BearerStrategy   = require('passport-azure-ad').BearerStrategy;
    const client           = redis.createClient()
    
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({ extended: true }));
    app.use(expressValidator());
    
    app.set('view engine', 'ect');
    app.engine('ect', ectRenderer.render);
    app.use(compression())
    app.use(express.static(__dirname + '/public', {
    	 maxAge: 2419200 ,
    	etag: false}));
    app.use(session({
    	  store: new RedisStore({
    		  host: '10.0.0.4',
    		  port: 6379,
    		  client: client
    		}),
        secret:'mostsecuresecretintheworld',
        saveUninitialized: true,
        resave: false,
        cookie: {
    	    path: '/',
    	    httpOnly: false,
    	    secure: true,
    	    maxAge: null
    	  }
    }));
    
    app.use(passport.initialize());
    app.use(passport.session());
    app.use(morgan('dev'));
    
    app.use(lusca({
      csrf: false,
      xframe: 'SAMEORIGIN',
      p3p: 'ABCDEF',
      xssProtection: true,
      nosniff: true,
      hsts: { maxAge: null, includeSubDomains: true, preload: true }
      //csp: { }
    }));
    
    passport.serializeUser(function(user, done) { console.log("serializeUser"), done(null, user) });
    passport.deserializeUser(function(id, done) { console.log("deserializeUser"), done(null, id) });
    
    passport.use(new OIDCStrategy({
    
        identityMetadata: secrets.azureOpenID.identityMetadata,
        clientID: secrets.azureOpenID.clientID,
        responseType: secrets.azureOpenID.responseType,
        responseMode: secrets.azureOpenID.responseMode,
        redirectUrl: secrets.azureOpenID.redirectUrl,
        allowHttpForRedirectUrl: secrets.azureOpenID.allowHttpForRedirectUrl,
        clientSecret: secrets.azureOpenID.clientSecret,
        validateIssuer: secrets.azureOpenID.validateIssuer,
        isB2C: secrets.azureOpenID.isB2C,
        issuer: secrets.azureOpenID.issuer,
        passReqToCallback: secrets.azureOpenID.passReqToCallback,
        scope: secrets.azureOpenID.scope,
        loggingLevel: secrets.azureOpenID.loggingLevel,
        nonceLifetime: secrets.azureOpenID.nonceLifetime
      },
      function(iss, sub, profile, accessToken, refreshToken, access_token, done) {
        if (!profile._json.oid) {
          return done(new Error("No oid found"), null);
        }
        process.nextTick(function () {
         var customProfile = {
           id: profile.id,
           oid: profile._json.oid,
           globalId: profile._json.upn.split("@")[0],
           name: profile._json.name,
           email: profile._json.upn,
           refresh_token: refreshToken,
           access_token: accessToken,
           expires_on: access_token.expires_on,
           ext_expires_in: access_token.ext_expires_in
         };
             console.log(customProfile)
          return done(null, customProfile);
        });
    }));
    passport.use(new BearerStrategy({
        identityMetadata: secrets.azureOpenID.identityMetadata,
        clientID: secrets.azureOpenID.clientID,
        responseType: secrets.azureOpenID.responseType,
        responseMode: secrets.azureOpenID.responseMode,
        redirectUrl: secrets.azureOpenID.redirectUrl,
        allowHttpForRedirectUrl: secrets.azureOpenID.allowHttpForRedirectUrl,
        clientSecret: secrets.azureOpenID.clientSecret,
        validateIssuer: secrets.azureOpenID.validateIssuer,
        isB2C: secrets.azureOpenID.isB2C,
        issuer: secrets.azureOpenID.issuer,
        passReqToCallback: secrets.azureOpenID.passReqToCallback,
        scope: secrets.azureOpenID.scope,
        loggingLevel: secrets.azureOpenID.loggingLevel,
        nonceLifetime: secrets.azureOpenID.nonceLifetime
      },
      function(token, done) {  }
    ));
    
    function authenticationMiddleware () {
      return function (req, res, next) {
        if (req.isAuthenticated()) {
          return next()
        }
        res.redirect('/login')
      }
    }
    
    app.get('/login', passport.authenticate('azuread-openidconnect', {  failureRedirect: '/', domain_hint: 'example.com', resourceURL: 'https://my.example.com/'}), function(req, res) { res.redirect('/') });
    app.post('/auth/openid/return', passport.authenticate('azuread-openidconnect', { successRedirect: '/', failureRedirect: '/login', domain_hint: 'example.com'}));
    
    app.get('/logout',
        function(req, res){
         req.session.destroy()
         req.logout()
         //res.redirect('/')
        res.redirect('/notAuthorized');
    });
    app.get('/notAuthorized',
        function(req, res){
          res.json({ Logged: false })
    });
    app.get('/', authenticationMiddleware(),
        function (req, res){
          res.render('index');
    });
    
    const certOptions = {	key: fs.readFileSync(__dirname + '/certs/server/my-server.key.pem', 'utf8'), cert: fs.readFileSync(__dirname + '/certs/ServerCertificate.crt', 'utf8'), ca: [ fs.readFileSync(__dirname + '/certs/Intermediate1.crt', 'utf8'), fs.readFileSync(__dirname + '/certs/Intermediate2.crt', 'utf8') ] };
    //http.createServer(app).listen(80)
    https.createServer(certOptions, app).listen(443)
    console.log("Server is running ...")

Do you have any idea why? thanks a lot

**Comment by lovemaths** [comment]
@makromat I guess the session is not configured properly, so session is not added to req before it comes to passport. The following config seem to work for me:

```
const redis = require('redis');
const RedisStore = require('connect-redis')(expressSession);
const client = redis.createClient();

app.use(expressSession({
    secret: 'ssshhhhh',
    // create new redis store.
    store: new RedisStore({ host: 'localhost', port: 6379, client: client,ttl :  260}),
    saveUninitialized: false,
    resave: false
}));
```

**Comment by lovemaths** [comment]
@makromat Closing the issue. Please reopen the issue if the problem persists. Thanks.
