### ISSUE TITLE
Some users seeing collectInfoFromReq error upon login though ADFS

### ISSUE THREAD

**Issue by jbhue** [AzureAD/passport-azure-ad#289]
I want to keep this issue very light at first and add information as needed. 

I have a set of users they seem to be able to authenticate through ADFS fine and never experience an issue. I also have some users who can sometimes login but most of the time get  an error.

The error occurs after they successfully go through the login process in ADFS but then are sent back to my website and are directly to the failureRedirect url I have setup for the middle ware.

When a user experiences the error described above I will see the following error in the logs from this package: 

`authentication failed due to: In collectInfoFromReq: invalid state received in the request`

What exactly does this error mean? Where should I be making changes to solve this issue? I have even taken over a users computer and logged in using my ADFS credentials and it worked fine. This leads me to believe its an ADFS issue; Where should i start looking in that context?

**Comment by lovemaths** [comment]
@jbhue We generate a state value and send it to authority (ADFS in your case) in the login request as a query parameter. The authority should send back the same state value in the response. If passport-azure-ad doesn't see the same state, the authentication will fail.

Can you check the fiddler trace, see if the state sent is the same as the state received. If you have trouble checking it, you can send the fiddler trace to my email (sijliu@microsoft.com), I can take a look. Thanks.

**Comment by jbhue** [comment]
@lovemaths I would like to try looking at the trace myself first as I don't want to send away any sensitive data by accident. Would you mind telling me the name of the query parameter used for this state check so I can do the check myself?

**Comment by lovemaths** [comment]
@jbhue First look for a GET request to your ADFS authorization endpoint, which looks like
 
```
GET https://.... /oauth2/authorize?redirect_uri=<your_redirect_uri>&response_type=<your_response_type>&response_mode=<your_response_mode>&client_id=<your_client_id>&state=<Copy this value>...
```

Copy the value of the 'state' query parameter.

Then look for POST request to your redirect_uri (assume you use form_post as the response_mode), it is like:

```
POST <your_redirect_uri>

state=...&code=...
```
It has a state parameter in the body. Compare this 'state' value with the previous 'state' value.

**Comment by jbhue** [comment]
@lovemaths Thank you for the very clear explanation.

I have had the troubled user login while Fiddler was running. I have compared the state query parameter in the GET request to the state parameter in the body of the returning POST request. They are exactly the same. I honestly expected for this to be the issue seeing as your explanation of the error seems to point in this direction.

**Comment by lovemaths** [comment]
@jbhue So the user still gets the same error even though the two state values are the same? 

We do the state validation the following way: We save state in express session before we send it, and once we receive the state, we will try to retrieve and remove it from express session. The max number of state we keep in session is 10 for each user, and each state in session expires and will be deleted after 1 hour.

(1) did you set nonceLifetime in your strategy configuration instead of using the default one. This controls how long we keep state in session.

(2) is this a web farm scenario? If so do you have the same express session across all servers?

**Comment by lovemaths** [comment]
@jbhue We released a new version of passport-azure-ad today (v3.0.6), which removes the dependency on express session for state validation. With this new release we can do state validation via cookie encryption and decryption. This might solve your issue directly. 

To use this feature, you can change the app the following way:

First add the four options in your strategy options. For `cookieEncryptionKeys` you can provide as many key/iv pairs as you want. We always use the first pair to encrypt cookie, but we try every pair to decrypt cookie, so this allows you to do key rollover. key can be any string of length 32, iv can be any string of length 12. Internally we use AES-256-GCM algorithm for the encryption and decryption.

```
  passport.use(new OIDCStrategy({
    ...
    nonceLifetime: 600,  // state/nonce cookie expiration in seconds
    nonceMaxAmount: 5,   // max amount of state/nonce cookie you want to keep (cookie is deleted after validation so this can be very small)
    useCookieInsteadOfSession: true,  // use cookie, not session
    cookieEncryptionKeys: [ 
      { 'key': '12345678901234567890123456789012', 'iv': '123456789012' },
      { 'key': 'abcdefghijklmnopqrstuvwxyzabcdef', 'iv': 'abcdefghijkl' }
    ],  // encrypt/decrypt key and iv, see `cookieEncryptionKeys` instruction in section 5.1.1.2
  },
    // any supported verify callback
    function(iss, sub, profile, accessToken, refreshToken, done) {
    ...
  });
```

Second wherever you use
```
passport.authenticate('azuread-openidconnect', {...}),
```
change it to
```
function(req, res, next) {
  passport.authenticate('azuread-openidconnect', { response: res, ... })(req, res, next);
},
```

**Comment by jbhue** [comment]
@lovemaths We have multiple servers and processes of node running but the state is managed through express sessions and stored in a database. I have not messed with the nonceLifetime at all.

Thank you for your detailed explanation of how the new update will help my case. We recently went in another direction and are no longer using ADFS and by extension this package. If we ever switch back or I come across some excess free time I will download the latest version and see if that solves it.

**Comment by lovemaths** [comment]
@jbhue Thanks for letting me know.

**Comment by billytrend** [comment]
We are seeing the same issue under similar circumstances as @jbhue , does anyone know how to resolve this or what might be causing it?
