### ISSUE TITLE
After sign out protected web api still available

### ISSUE THREAD

**Issue by mmikirtumov** [AzureAD/passport-azure-ad#292]
Out application use OIDCStrategy for this library. In Azure AD we use implicit flow and OpenID logic. When user login and get access_token after calling the protected resource all works fine. 
When user log out from Azure AD and we send the request to protected resource with the old value of access_token the API response the same way, and library pass to the next middleware.
Could you please help us what we do wrong?

**Comment by lovemaths** [comment]
@mmikirtumov This is expected behavior of access token. access token can be used as long as it is not expired, it has nothing to do with whether the user is logged in or not. I think access token is valid for 1 hour after issuance. I think you might want to store the access token per user, and delete the corresponding access token before logging out a user.

**Comment by mmikirtumov** [comment]
@lovemaths Thank you for your response. I remove token from browser and this token does not available for user, but when you have token you can access to specific resource during 1 hour even if user log out. So you mean that even user log out from Azure AD, this token will be valid until expire time?

**Comment by lovemaths** [comment]
@mmikirtumov Yes that's right. Access token can be used as long as it is not expired.

**Comment by mmikirtumov** [comment]
@lovemaths do you know is it correct behaviour in the scope of OpenID standarts?

**Comment by lovemaths** [comment]
@mmikirtumov Yes, this is the correct behavior in the scope of OpenID standard. Access token is issued by identity provider, but consumed by resource server (which is usually different from identity provider). Resource server only needs to validate the claims and expiration encoded in the access token string. Once issued, access token can be used as long as it is not expired, therefore access token is usually short lived and must be stored securely.

**Comment by mmikirtumov** [comment]
Thank you @lovemaths

**Comment by szarouski** [comment]
Is it possible to control token expiration time?

**Comment by mmikirtumov** [comment]
@szarouski You mean after creation of token you want to change the expiration time?
