### ISSUE TITLE
Receive id_token instead of access_token despite proper responseType and clientSecret.

### ISSUE THREAD

**Issue by dkushner** [AzureAD/passport-azure-ad#294]
**Version**: 3.0.6

**Behaviour**: While attempting to authenticate via the OpenID protocol, I provide a `responseType` of `'code id_token'` and my client secret to the configuration. According to the documentation this should permit me to receive an access_token from the endpoint. However, the only tokens I receive when the flow completes are an id_token and a refresh_token. 

**Expectation**: I should receive an access_token after exchanging the authorization code with the token endpoint while a client secret is present in the configuration and the `responseType` includes code.

I know that the client secret is being used because of this log line:
```
{"name":"AzureAD: OIDC Passport Strategy","hostname":"xxxxxx","pid":5871,"level":30,"msg":"In _getAccessTokenBySecretOrAssertion: we are using client secret","time":"2017-04-28T18:58:53.828Z","v":0}
```
I know that the access_token isn't received from the token endpoint because of this log line:
```
{"name":"AzureAD: OIDC Passport Strategy","hostname":"xxxxxx","pid":5871,"level":30,"msg":"received access_token:  undefined","time":"2017-04-28T18:59:10.411Z","v":0}
```

**Comment by lovemaths** [comment]
@dkushner It seems Azure AD didn't return an access token, could you give me the following information?
(1) what is the metadata endpoint are you using? Is it v1 or v2?
(2) did you specify any resource? any scope? what resource are you supposed to get access token for?

**Comment by dkushner** [comment]
@lovemaths, thanks for the quick reply. I'm currently using:

  https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration

The scopes I'm specifying are currently:

```
['openid', 'profile', 'offline_access', 'email']
```

**Comment by lovemaths** [comment]
@dkushner The reason is you didn't specify a resource in scope. If you specify a resource like 'https://graph.microsoft.com/mail.read' in scope, you will get an access token. In other words, try scope = ['openid', 'profile', 'offline_access', 'email', 'https://graph.microsoft.com/mail.read'].

The reason you got an refresh token is that you specified 'offline_access' in scope, but I am not sure what that refresh token is used for though.

**Comment by lovemaths** [comment]
@dkushner What is the resource you are trying to get the access token for?

**Comment by dkushner** [comment]
@lovemaths, I was attempting to access `https://graph.microsoft.com/user.read` but had placed the resource URL in the resource section of the options. I appreciate your help with your last response and the rapid replies. Thanks!
