### ISSUE TITLE
Error: a key with kid %s cannot be found

### ISSUE THREAD

**Issue by oreporan** [AzureAD/passport-azure-ad#301]
According to passport documentation you can authenticate against 2 strategies like so:

`passport.authenticate([StrategyA, StrategyB], {session: false})`

However when StrategyA is `passport-azure-ad` BearerStrategy, and the token on the request corresponds to StrategyB. It never reached StrategyB because an exception is thrown:

```js
Error: a key with kid %s cannot be found
    at Metadata.generateOidcPEM (/.../node_modules/passport-azure-ad/lib/metadata.js:146:11)
    at Strategy.jwtVerifyFunc [as jwtVerify] (/.../node_modules/passport-azure-ad/lib/bearerstrategy.js:291:23)
    at async.waterfall (/.../node_modules/passport-azure-ad/lib/bearerstrategy.js:462:19)
```
There seems to be no `err` variable in the BearerStrategy:
```js
const clientAuthenticationStrategy = new BearerStrategy(options,
    (token, done) => {
        if (!token) return done("no token", null)
        return done(null, token);
    });
```

**Comment by lovemaths** [comment]
@oreporan Thank you for your contribution, we will add your fix to our code base.

**Comment by oreporan** [comment]
Any eta on this merge?

**Comment by lovemaths** [comment]
@oreporan Sorry for the delay. Could you make your PR against our `dev` branch instead of `master`? I will merge your PR then. Thank you!

**Comment by oreporan** [comment]
Yes, I could do that. 
Though for the future, you should probably make dev your default branch or else anyone who makes a pull request will always clone the wrong branch..

<img width="830" alt="screen shot 2017-06-10 at 9 56 57" src="https://user-images.githubusercontent.com/2146999/27000834-34dc9546-4dc3-11e7-9b79-4258a181f6d8.png">

**Comment by lovemaths** [comment]
@oreporan Released new version with the change in npm.
