### ISSUE TITLE
Test Credentials for Unit Tests

### ISSUE THREAD

**Issue by jamespegg** [AzureAD/passport-azure-ad#303]
I'm looking to unit test my express app using Supertest & Jasmine. At the moment, I'm having to use a real token in order to verify the requests.

Is there a way to use a test token to validate requests, or is there a preferred way to structure unit tests?

**Comment by lovemaths** [comment]
@jamespegg We have two kinds of tests:
(1) mock tests using 'chai-passport-strategy'. This tool is specific for testing passport.js strategies. The tests are in test/Chai-passport_test folder.
(2) end to end tests using selenium and chrome driver. Here in the test we start an express server for each test case, manipulate the browser to make a request, record the response result in some html page, then fetch the result from html and do the comparison. Everything is automated. The tests are in test/End_to_end_Test folder.

**Comment by jamespegg** [comment]
Thanks @lovemaths , however that doesn't really answer my question. I'm not looking to run the unit tests that you've already got, I need to unit test my own application that uses this library.

Ideally we shouldn't need to include a real AD token in our own unit tests to check whether this library is running. Do you have any recommendations on mocking Azure AD or to generate a test token that will validate?

**Comment by lovemaths** [comment]
@jamespegg The only way I know is through end to end test using selenium and chrome driver. You can look at the pattern of the end to end tests we have (test/End_to_end_Test folder). We have test applications there, and we test the web apps directly without mocking anything. We use selenium and chrome driver to help us enter the user name and password programmatically, so everything can be automated.
