### ISSUE TITLE
Create a Typescript Declaration file for this project

### ISSUE THREAD

**Issue by TofuDaCat** [AzureAD/passport-azure-ad#304]
Affected Branch - **master**

This project atm does not have a typings file. A strongly typed declarations file would be useful for those using Typescript.

Ref - https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

**Comment by oreporan** [comment]
frankly its a bit dissapointing that a microsoft library doesn't have typescript on its own modules...

**Comment by Ephasme** [comment]
Is this abandoned?

**Comment by Robula** [comment]
Probably abandoned like most of Microsoft's stuff on GitHub...

**Comment by ADRDev** [comment]
Still nothing?

**Comment by pkanher617** [comment]
We are working on an update for the passport library that will encompass this feature, you can track the progress [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9).
