### ISSUE TITLE
"Unauthorized" gives no details as to why authentication failed. Very frustrating.

### ISSUE THREAD

**Issue by AskYous** [AzureAD/passport-azure-ad#305]
I'm trying to use this for my application, but I get the following response with zero information as to how this happened or how to fix it. I don't know what I did wrong or where to start in fixing this!

**Code:**
![image](https://cloud.githubusercontent.com/assets/791996/26379704/8b9313d0-3fcf-11e7-8303-8a2154d3a112.png)

**Outcome:**
![image](https://cloud.githubusercontent.com/assets/791996/26379710/99781cd4-3fcf-11e7-92ba-5aa9766ba440.png)

There's no error message in the front-end, nor in my server. It just says "unauthorized." I need some detail.

**Comment by lovemaths** [comment]
@AskYous Add "loggingLevel" in the OIDCStrategy option like the following, and you will see all the logs in your server console.

```
passport.use("..", new OIDCStrategy({
    ...
    ...
    'loggingLevel': 'info'                        // <===== add the option to turn on logging
  }, function(...) {
  }));
```

**Comment by AskYous** [comment]
@lovemaths thank you!

**Comment by mmustala** [comment]
Please add a section "Troubleshooting" into the readme and tell to enable the logging.
