### ISSUE TITLE
How do I get the user's profile from encrypted data?

### ISSUE THREAD

**Issue by AskYous** [AzureAD/passport-azure-ad#306]
Hello,

I'm not sure where to ask this, so I'll ask here. In the verify function, I have a bunch of encrypted data. And the `profile` json object is all `undefined` data. How do I get the user's info from this? All I see is `undefined` data. See the parameters of the verify function below:

![image](https://cloud.githubusercontent.com/assets/791996/26420278/faa8b624-4076-11e7-9650-034c9d90d662.png)

I also tried `jwt.decode(params.id_token, "", true)` but all I get from that is more encrypted data.

Thank you in advanced.

**Comment by lovemaths** [comment]
@AskYous You can access the claims in ```id_token``` using ```profile._json```, for instance, ```profile._json.email```. If you want to look at the content of ```id_token``` directly without any software, you can go to https://jwt.io/ and paste your ```id_token``` there. The reason you got ```undefined``` for ```name``` etc is that these claims are not provided in ```id_token``` returned from AAD. 

No data is encrypted. ```sub``` is the id of the logged-in user. It seems AAD didn't give much user information in ```id_token```.

**Comment by AskYous** [comment]
When I try to access the user's profile information, I get more data that I don't know how to read. I don't know what this is. Am I supposed to somehow get the profile information from this? When I used jwt.io or `profile__json`, they both give me this (in json format):

```
aio:"ASQA2/8DAAAA9izoKIW8XqQDYl9RtDbFsGHF+u6rZ8dh8lrRogtkpVs="
aud:"b6c8879b-5c72-43d3-b82d-3d8a7252f3b1"
exp:1495654966
iat:1495651066
iss:"https://login.microsoftonline.com/3f0e69e0-eb38-4eb2-b4ee-52919719d31e/v2.0"
nbf:1495651066
nonce:"eDmNIucvJCUp/S+EtsRznPgXrD9XmSi4"
sub:"IwhgMqhikKHdblRYXuYgPJrxr6kQECBKXqjFNflTCXM"
tid:"3f0e69e0-eb38-4eb2-b4ee-52919719d31e"
uti:"IW8rFAATxUyZho0eyEkIAA"
ver:"2.0"
```

**Comment by lovemaths** [comment]
@AskYous The only claim about the user in this ```id_token``` is ```sub```, which is the unique id for your user in your tenant. The rest claims are for token validation purposes, not for you to read. Here is the document on claims: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-tokens

There are two possible reasons why you don't get more claims about the user profile.
(1) you didn't provide the information about the user in AAD, like name, last name etc.
(2) AAD doesn't return the user profile claims, and you need to call graph api to fetch more information. This is beyond my scope of knowledge though.

**Comment by AskYous** [comment]
Hmm... I fixed it but I don't know why it's working now.

Before, I used [passport-azure-ad-oauth2](https://github.com/auth0/passport-azure-ad-oauth2), and that would give me the access_token which I would use jwt, and it returns the user's profile with the claims filled in. But I stopped using it because it didn't allow me to enter the `scope` so the data I received was limited.

For some reason, passport-azure-ad-oauth2 was able to retreive the users profile, but passport-azure-ad didn't. This was the settings I gave it and it worked:

```
  "authorizationURL": "https://login.microsoftonline.com/common/oauth2/authorize",
  "tokenURL": "https://login.microsoftonline.com/common/oauth2/token",
  "clientID": "<client-id>",
  "clientSecret": "<client-secret>",
  "callbackURL": "http://localhost:1337/login/callback",
  "resource": "https://<our-company>.sharepoint.com",
  "scope": ["email", "offline_access", "profile"] // does  nothing
```

I suppose the main difference is because the authorization url in the working version was pointing to the `/common` url. So I tried using `common` now but it said I need to enter a `tenantIdOrName`, so I did, and now it works!

**Comment by lovemaths** [comment]
@AskYous The reason is you are using v1 endpoint in passport-azure-ad-oauth2 options, but you are using v2 endpoint for passport-azure-ad. As you can see, you have the word ```v2.0``` in the metadataUrl in passport-azure-ad options. The two endpoints are completely different. You will get the user profile in passport-azure-ad as well if you remove the ```v2.0```. What do you need scope for?

**Comment by AskYous** [comment]
Oh ok. Is passport-azure-ad not for v2? Or is there an updated version of this repository for v2? Sorry I'm confused.

I used scope to tell the server what information I want from the user. I want to get their name, email, and perhaps other information in the future such as profile picture or manager. I switched the endpoint to v1 and it worked better with passport-azzure-ad. I'm guessing v2 is better. Does passport-azure-ad support the v2 endpoint?

**Comment by lovemaths** [comment]
@AskYous passport-azure-ad supports v2 endpoints. 

The reason you don't get the user profile expected from v2 endpoint is not a library problem. v1 endpoint has an user info endpoint, passport-azure-ad and passport-azure-ad-oauth2 both go there to fetch the user profile json. v2 endpoint doesn't have an user info endpoint, so you can only get limited user profile from ```id_token```. In your case, only the ```sub``` claim.

To get more info of a user for v2 endpoint, you have to call graph api. First add ```User.Read``` to ```scope```, do a ```npm install superagent --save```, and try the following code in your verify callback.

```
var agent = require('superagent');

passport.use(new OIDCStrategy(options,   
  function(iss, sub, profile, accessToken, refreshToken, done) {
    agent
     .get('https://graph.microsoft.com/v1.0/me')    // <==== use the accessToken to call graph api
     .set('Authorization', 'Bearer ' + accessToken)
     .end((err, resp) => {
        console.log(resp.body);                //<=== get the full profile for the user in the response
        profile.fullProfile = resp.body;
        return done(null, profile);
     });
  });
```

**Comment by AskYous** [comment]
Thanks @lovemaths. I understand the difference between v2 and v2 now. Basically v1 offers user information, and v2 offers a token to get user information via the graph API correct? Now I understand where the graph API comes in.
