### ISSUE TITLE
Verify id_token outside context of a request

### ISSUE THREAD

**Issue by rrdelaney** [AzureAD/passport-azure-ad#307]
In my app I need to verify the signature of an `id_token` outside the context of passport.

I create the strategy like so:

```js
  const strategy = new PassportAzureAd.OIDCStrategy(
    PASSPORT_CONF,
    (iss, sub, profile, claims, accessToken, refereshToken, params, done) => {
      profile.access_token = params.access_token
      done(null, profile)
    }
  )
```

but eventually I want to be able to verify an `id_token` like:

```js
const verify = id_token => {
  const isTokenValid = strategy.verifySigniture(id_token)

  return isTokenValid
} 
```

Is there any way to do this? Alternatively if I can access the key used to verify tokens I could use a JWT package to manually verify.

**Comment by lovemaths** [comment]
@rrdelaney You need to  manually verify the signature. 

(1) create a metadata object (lib/metadata.js) with the metadataUrl, call [metadata.fetch](https://github.com/AzureAD/passport-azure-ad/blob/master/lib/metadata.js#L154). This way you will get all the keys in metadata. Note the `fetch` function is async.

(2) get the key id `kid` or `x5t` from the `id_token` header, then call [metadata.generateOidcPEM](https://github.com/AzureAD/passport-azure-ad/blob/master/lib/metadata.js#L105) to generate the private key corresponding to the `kid` or `x5t`. You can take a look [our code to validate an id_token](https://github.com/AzureAD/passport-azure-ad/blob/master/lib/jsonWebToken.js#L53) to learn how to verify the signature after getting the key.
