### ISSUE TITLE
Need a way to dynamically set redirectUrl

### ISSUE THREAD

**Issue by AskYous** [AzureAD/passport-azure-ad#308]
We need a way to dynamically set the redurectUrl. The scenario is the following:

- In production, we need the redirectUrl to be `https://www.<mywebsite>.com/login/callback`.
- In development in my machine, we need the redurectUrl to be `http://localhost:1337/login/callback`.
- In development in my colleague's machine, we need the redirectUrl to be `http://localhost:81/login/callback`.
- In our testing server, we need the redirectUrl to be `http://10.xx.xx.xx/login/callback`.

And I don't know the url of the website at build time of my application. So I can't put a variable or something.

If I can set the `redirectUrl` to `/login/callback`, it would be much easier. When I try to do that, it errors saying that the redirectUrl needs to start with `http` or `https`.

**Comment by lovemaths** [comment]
@AskYous This is not possible. We must know the redirectUrl in advance, because we have to include the redirectUrl in the login request sent to Azure AD. Azure Ad checks if the redirectUrl matches one of those registered. Therefore redirectUrl must be exactly the same with one of those registered.

**Comment by AskYous** [comment]
> In fact you can override the redirectUrl using extraAuthReqQueryParams option.

That's perfect! Thanks!

**Comment by AskYous** [comment]
@lovemaths I just tested this and received the following error:

` The reply address '<initiallRedirectUrl>' does not match the reply address '<theSetRedirectUrl>' provided when requesting Authorization code.`

Where initialRedirectUrl is the one I put in `new OAuth2Strategy({ ... })` and theSerRedirectUrl is the one set using the `extraAuthReqQueryParams`. So it seems it's useless. I don't know.

But I think you can implement allowing the `redirectUrl` to be dynamical because in the middleware, you can always read `req.baseUrl`. So if I initialize passport and use `new OAuth2Strategy({ redirectUrl: '/login/callback' })`, you can find the initial part of the redirectUrl using `'req.baseUrl' + options.redirectUrl` if the redirectUrl starts with a `/`.

This is used using [`req.baseUrl`](https://expressjs.com/en/api.html#req.baseUrl).

**Comment by lovemaths** [comment]
@AskYous I forgot you are using authorization code flow. This flow we send two requests (login request and token request) to Azure AD, so we have to override `redirect_uri` twice. I tested the following, it should work for you.

```
app.get('/login', 
  passport.authenticate('..',  { extraAuthReqQueryParams : {  'redirect_uri' : 'the one you want' } });
  ...
);
app.post('/login/callback', 
  passport.authenticate('..',  { extraTokenReqQueryParams : {  'redirect_uri' : 'the one you want' } });
  ...
);
```

**Comment by Mahan-F** [comment]
@lovemaths Is this solution that you proposed still possible? 
I need to do this but can't seem to figure out how to make it work.

**Comment by manthanappveen** [comment]
@lovemaths The solution you mentioned is still having the same error. Is there any other way?

**Comment by nilsmehlhorn** [comment]
The solution eventually worked for me, make sure that the override in the callback uses the property `extraTokenReqQueryParams` whereas the first override that kicks off the login uses `extraAuthReqQueryParams` - I didn't notice they're different at first.
