### ISSUE TITLE
Network requests

### ISSUE THREAD

**Issue by newtack** [AzureAD/passport-azure-ad#311]
This is more of a documentation question. 
Will this library make network calls in validating bearer tokens, and if so, when and how often?

**Comment by lovemaths** [comment]
@newtack Token validation itself doesn't make network call. However, token validation happens in `passport.authenticate`, and `passport.authenticate` may make network calls. 

When you call `passport.authenticate`, we will try to load metadata from memory cache. If we don't find it in memory cache, we will make network call to load it and save it to cache. The memory cache is kept for 30 minutes.
