### ISSUE TITLE
Group removed not refleacting

### ISSUE THREAD

**Issue by navneetccna** [AzureAD/passport-azure-ad#313]
I removed user from a group but when i refresh my web page it still showing me the group in the response
I noticed that when i restart my server than only removed group is not coming in response.

Can you tell me how can i force to update group without restarting the server ?

**Comment by lovemaths** [comment]
@navneetccna What is `group`? Can you give me more details on how you used this library to get a `group` and remove a user from a `group`?

**Comment by navneetccna** [comment]
Azure groups for managing users. Users and groups - All groups under the Microsoft_AAD_IAM


Claim by  OIDC Passport Strategy using 
responseType: 'code id_token', 
scope: ['openid', 'profile', 'email'],

**Comment by lovemaths** [comment]
@navneetccna So you mean the `group` info is provided in `id_token` claims?

Once the user is logged in, passport remembers the claims from the `id_token`, and uses these claims until user is logged out or `passport.authenticate` is called again. Therefore you need to call `passport.authenticate` again to get a new `id_token` after you remove a user from a `group`.

**Comment by navneetccna** [comment]
How can i refresh the token again ? How i know that admin change the group using code ?

**Comment by lovemaths** [comment]
@navneetccna You can call passport.authenticate to refresh the token. I think you want to call passport.authenticate to get an updated id_token everywhere you want the group info. 

Just out of curiosity, which claim in id_token provides the group info?

**Comment by lovemaths** [comment]
@navneetccna Closing this issue since this is not actionable for the library.
