### ISSUE TITLE
Support for multiple AD

### ISSUE THREAD

**Issue by gnaeser** [AzureAD/passport-azure-ad#316]
Trying to set up a server where multiple Azure AD can be used is not possible as the cache-manager will be shared between all instances of the oicdstrategy.

Moving the require inside the Strategy.prototype.setOptions function solves the problem for servers running one instance of the server. However, this may not solve the problem when clustered servers are used (as the cache will be memory local to the instance that initiated the authentication). The memory-cache allows for other storages to be used like, e.g., redis or the req.session, and allowing the strategy to decide which storage to use may eliminate this problem.

Any thoughts?

**Comment by lovemaths** [comment]
@gnaeser cache-manager shouldn't cause any problem, since it is only used to store the metadata fetched from identityMetadata url, and the cache key is the url itself. It doesn't make much difference whether each oidcStrategy has its own cache-manager or they are using a shared one.

How did you use multiple oidcStrategy?

**Comment by gnaeser** [comment]
I connect to two AD by doing the following in my (express) server.js
```javascript
require('./authentOIDC')(app, 'https://localhost:8080', 'ad1', 'dir-id-1', 'app-id-1', 'secret-1');
require('./authentOIDC')(app, 'https://localhost:8080', 'ad2', 'dir-id-2', 'app-id-2', 'secret-2');
```

where authentOIDC.js does

```javascript
module.exports = function(app, server, appUrl, directoryId, applicationId, clientSecret) {
    var creds = {
        returnURL: server + appUrl + '/return',
        identityMetadata: 'https://login.microsoftonline.com/' + directoryId + '/.well-known/openid-configuration',
        clientID: applicationId,
        clientSecret: clientSecret,
        skipUserProfile: true,
        responseType: 'id_token code',
        responseMode: 'query'
};

   var OIDCStrategy = require('passport-azure-ad').OIDCStrategy;
    passport.use(appUrl, new OIDCStrategy(
        { callbackURL: creds.returnURL,
          redirectUrl: server + appUrl + '/return',
          realm: creds.realm,
          clientID: creds.clientID,
          clientSecret: creds.clientSecret,
          audience: creds.clientID,
          oidcIssuer: creds.issuer,
          identityMetadata: creds.identityMetadata,
          skipUserProfile: creds.skipUserProfile,
          responseType: creds.responseType,
          responseMode: creds.responseMode
        },
        function(iss, sub, profile, accessToken, refreshToken, done) {
            process.nextTick(function () {
                return done(null, profile);
            });
        }
 //and then the routes are configured and serialization is coded
}
```

but doing it this way will only allow one of the ADs to be used if the cache is "global"; only one of the applications will be remembered.

Am I doing it the wrong way? I want my server to allow customers and auth using their own Azure ADs.

**Comment by lovemaths** [comment]
@gnaeser I cannot tell anything from this setting. Please take a look at the answer I gave to this [stackoverflow question](https://stackoverflow.com/questions/43885351/multiple-policies-for-oidcstrategy-using-passport-azure-ad/43945140#43945140). That approach works with multiple OidcStrategy.

**Comment by gnaeser** [comment]
Thanks for the link, I'll confirm that the described method works for me. (It does however not solve the problem in the code...)

The issue that the thread describes is.most likely the same as I ran into; creating multiple instances of the policy will have them share data. It's an easy fix to move the require on the cache to where it is actually used (rather than having it among all global requies) and this actually allows for multiple instances of the strategy to be created).

**Comment by gnaeser** [comment]
Yes! Explicitly (re)naming the strategies works! So, I'll continue down that path. Thanks!
