### ISSUE TITLE
Improve discoverability of npm package

### ISSUE THREAD

**Issue by nicolehaugen** [AzureAD/passport-azure-ad#326]
Today, unless you are specifically searching for Azure AD, it is difficult to find this package.  To improve discoverability and make the value proposition of this package clearer, consider the following changes:

1.) A huge value-add of using AAD is that it also allows you to hook-up social authentication; however, this isn't explicitly called out in the documentation for this package.  Since this is important functionality that would benefit many node.js devs, this should be highlighted right at the beginning of the documentation.  Also, the doc should be updated to mention the variety of identity providers that are supported, such as Facebook, Google, etc.  

2.) Adding to the above bullet, the tagging of this package should be improved to include more general keywords that will help node.js devs discover this, such as "social auth", "facebook", "google", etc.  In addition, it would be beneficial to include "passport" as a tag too.

3.) The documentation shouldn't assume that node.js devs looking at this package are already familiar with AAD and Azure.  Here are a few specific examples of where this is being done:

- There is a lot of in-depth detail in the documentation for this package, but it would be helpful to have a high-level overview that explains the value-add of using this package before diving into the low level details.  Today, the value proposition is getting lost among the details (it may worth considering moving some of this documentation elsewhere, such as to MSDN to help simplify it?).

- Within the doc, there are links to the Azure portal.  For someone that isn't coming from an Azure background or that doesn't have a subscription, the doc should avoid providing links that they can't access.  Or, we need to provide some high-level info on how to gain a subscription.

These are a few examples that stood out, but the documentation as a whole would benefit from being reviewed from the perspective of a node.js dev that doesn't have knowledge of AAD\Azure.  And, with this in mind, the documentation should clarify why this package is useful to them.

**Comment by pkanher617** [comment]
We are working on an update for the passport library that will encompass this feature, you can track the progress [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9).
