### ISSUE TITLE
prompt admin_consent - Unsupported

### ISSUE THREAD

**Issue by rrubio** [AzureAD/passport-azure-ad#331]
Hi Guys,

Getting the following error when trying to use "prompt" AADSTS90023: Unsupported 'prompt' value.

`router.get('/login', passport.authenticate('azuread-openidconnect', { failureRedirect: '/', prompt: 'admin_consent' }),
  function(req, res) {
    log.info('Login was called in the Sample');
    res.redirect('/');
});
`

**Comment by lovemaths** [comment]
Could you give us the config (options) of the strategy? The error message from authentication endpoint says admin_consent is not supported for your configuration or your application.

**Comment by rrubio** [comment]
@lovemaths thanks for your quick response, but i think it's just a typo on the readme file. I'm now using the following and errors are gone.

> promt:'admin_consent'

**Comment by lovemaths** [comment]
@rrubio The typo is now fixed. Thank you for pointing it out!
