### ISSUE TITLE
Allow query parameters in the identityMetadata config key

### ISSUE THREAD

**Issue by herrkris** [AzureAD/passport-azure-ad#338]
Hey there,

the identity server I'm using has a query parameter in the URL. I saw that whenever you are concatenating URLs you don't check if a query parameter is already present. Would be super helpful to have this feature in place, since everything else is working awesomely! :)

I also provided a PR. Hope that helps! :)

Cheers,
Kris

**Comment by lovemaths** [comment]
@herrkris merged your PR to dev branch. Thank you for your contribution!
