### ISSUE TITLE
Cannot connect behind proxy

### ISSUE THREAD

**Issue by hsimah** [AzureAD/passport-azure-ad#341]
I develop behind a corporate proxy - this library does not set the agent on any requests to Azure.

I need to get this done for an internal project and so have forked the repo and added in a quick and dirty `https-proxy-agent` import to `oidcstrategy` and `metadata`. I will hopefully come back later and clean it up.

**Comment by HofmT** [comment]
@hsimah Hey, are you still working on it? Because I am currently dealing with the issue of working behind a proxy with azure passport and cannot solve it.
I tried to adapt your modifications butmy server crashes after I successfully log into Azure AD: Error message is: _Error: an HTTP(S) proxy server `host` and `port` must be specified!_
I have specified the proxy hardcoded by replacing _options.proxy_ in metadata.js  with the proxy url string.

**Comment by hsimah** [comment]
@HofmT if you reference my fork (https://github.com/hsimah/passport-azure-ad) from your npm package.json it should work. It's not pretty but it works for my employer's proxy.

**Comment by leitu** [comment]
@hsimah , your patch save my life, I had been struggle for weeks!

**Comment by hsimah** [comment]
@leitu glad it helped
@HofmT did you get it working? I have some spare time coming up and I will formalise this into a PR. Your use case would help me make a robust one.

**Comment by HofmT** [comment]
@hsimah To be honest I did not pursue it any further. I used a workaround which redirects the whole traffic via the proxy using global-tunnel.

**Comment by Dortamur** [comment]
I am also encountering this issue. At the moment we're using a similar global tunnel hack, but it would be cleaner if this could be defined specifically for passport-azure-ad.

For the "oauth" module, as of version 0.9.15, it allows setting of an Agent:
```js
var HttpsProxyAgent = require('https-proxy-agent');
var oauth2 = new OAuth2(...);
if (process.env['https_proxy']) {
  var httpsProxyAgent = new HttpsProxyAgent(process.env['https_proxy']);
  oauth2.setAgent(httpsProxyAgent);
}
```
(Source: https://github.com/ciaranj/node-oauth/issues/307)

However, while passport-oauth2 depends on oauth "0.9.x", passport-azure-ad depends specifically on "0.9.14", and so this capability is not available. In addition, passport-azure-ad doesn't store the oauth2 instance anywhere it can be called externally.

It would be really useful to be able to set either a proxy URL, or pass in an Agent, for calls done within the OIDC Strategy of passport-azure-ad.

**Comment by maxxt** [comment]
Has this issue been fixed?
I still get ECONNREFUSED errors behind corporate proxy.

**Comment by mplwork** [comment]
I have the same problem.

**Comment by mplwork** [comment]
> 
> 
> @HofmT if you reference my fork (https://github.com/hsimah/passport-azure-ad) from your npm package.json it should work. It's not pretty but it works for my employer's proxy.

@hsimah 
Is there anything else required? I can't get it working. I changed `package.json` to

```
 "passport-azure-ad": "hsimah/passport-azure-ad",
```
and after much fuzzing with git to actually load it (npm doesn't like cygwin) the result is still the same. No proxy is being used.

**Comment by hsimah** [comment]
@mplwork I am sure my fork has become stale by now. If you look at the changes I hope it is clear how I added proxy support.

Unfortunately I have changed jobs and no longer work at a company with a proxy, so there isn't a test scenario for me. Best of luck though.

**Comment by mplwork** [comment]
I am still fighting this. This whole issue is a real pain but I made some progress.

I had to change `package.json` (and use portable git instead of Cygwin's as npm messes up paths) to

```
 "passport-azure-ad": "hsimah/passport-azure-ad#feature/add_proxy_support"
```
as @hsimah 's patch lives in a branch. Unfortunately, the patch doesn't pick up the proxy setting from the usual env variables so I had to change `app.js`:

```
@@ -119,6 +126,8 @@ passport.use(new OIDCStrategy({
     useCookieInsteadOfSession: config.creds.useCookieInsteadOfSession,
     cookieEncryptionKeys: config.creds.cookieEncryptionKeys,
     clockSkew: config.creds.clockSkew,
+    loggingNoPII: false,
+    proxy: { port: 8888, host: 'localhost', protocol: 'http' }
   },
   function(iss, sub, profile, accessToken, refreshToken, done) {
     if (!profile.oid) {
```

Now the proxy is used, hurray! But it still doesn't work:

```
::1 - - [13/Nov/2018:17:52:32 +0000] "POST /auth/openid/return HTTP/1.1" 302 46 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0"
{"name":"AzureAD: OIDC Passport Strategy","hostname":"p01166818","pid":12224,"level":30,"msg":"authentication failed due to: In _authCodeFlowHandler: failed to redeem authorization code: read ECONNRESET","time":"2018-11-13T17:52:32.334Z","v":0}
_http_outgoing.js:491
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.res.setHeader (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\connect\lib\patch.js:134:22)
    at ServerResponse.res.set.res.header (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\express\lib\response.js:595:10)
    at ServerResponse.res.location (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\express\lib\response.js:725:8)
    at ServerResponse.res.redirect (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\express\lib\response.js:764:8)
    at allFailed (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport\lib\middleware\authenticate.js:145:20)
    at attempt (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport\lib\middleware\authenticate.js:180:28)
    at Strategy.strategy.fail (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport\lib\middleware\authenticate.js:297:9)
    at Strategy.failWithLog (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport-azure-ad\lib\oidcstrategy.js:1490:15)
    at async.waterfall (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport-azure-ad\lib\oidcstrategy.js:651:21)
    at C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport-azure-ad\node_modules\async\lib\async.js:52:16
    at C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport-azure-ad\node_modules\async\lib\async.js:1209:30
    at self._getAccessTokenBySecretOrAssertion (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport-azure-ad\lib\oidcstrategy.js:1197:16)
    at oauth2._request (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport-azure-ad\lib\oidcstrategy.js:1470:16)
    at ClientRequest.<anonymous> (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\oauth\lib\oauth2.js:162:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
```

I get a similar result if I use `global-tunnel-ng` instead of the patched `passport-azure-ad`.  What's next to hack?

**Comment by nonongodup** [comment]
getting same issue behind proxy."authentication failed due to: connect ECONNREFUSED . 
Cannot use passport js behind the proxy

**Comment by sergeytrasko** [comment]
Are there any plans to push changes from @hsimah to official repo? 
As a temporary solution we use the fork - it works well, however I would prefer to have official support in passport-azure-ad.

I believe there is a number of consumers (especially in enterprise segment) that have to work through proxy and they will benefit from this fix.

**Comment by hsimah** [comment]
I no longer work in the MS tech stack or behind a corporate proxy. I have updated my branch to the latest `dev`. Best of luck :)

**Comment by caramorsimon** [comment]
@hsimah thanks for the proxy change - I have re-merged against the current branch & tested behind non-authenticating proxy.

**Comment by hsimah** [comment]
@caramorsimon thanks for not letting the PR get stale.

**Comment by georgejdli** [comment]
Another workaround is to use the [global-proxy](https://www.npmjs.com/package/global-proxy) module.
```
//so passport can activate authZ code
// export GLOBAL_AGENT_HTTP_PROXY=<company proxy url>
...
const { bootstrap } = require('global-agent')
bootstrap()
```

**Comment by pkanher617** [comment]
Pull request #435 was merged, if this is still an issue please open a new issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose).
