### ISSUE TITLE
Any way to use without cookies/sessions?

### ISSUE THREAD

**Issue by timelf123** [AzureAD/passport-azure-ad#343]
We already use JWT for state, don't want to add another cookie. Anyone use this module without using sessions/cookies?

**Comment by timelf123** [comment]
For example, this is how we add our token to a cookie
```
        authCallback: function(req, res) {
            var payload = req.user;
            var escaped = JSON.stringify(payload);
            escaped = encodeURI(escaped);
            // We are sending the payload inside the token
            var token = jwt.sign(escaped, config.secret);

            res.cookie('token', token);

            var destination = req.redirect || config.strategies.landingPage;

            if(!req.cookies.redirect) {
                res.cookie('redirect', destination);
                res.redirect(destination);
            }
        },
```

**Comment by lovemaths** [comment]
@timelf123 This is not possible for OIDCStrategy. Session/cookie is required for `state` and `nonce` validation when user logs in for the first time. We use session/cookie to store `state` and `nonce` when we send authorization request to AAD. When we get response back from AAD, we retrieve `state` and `nonce` from session/cookie and compare them with the those in the response.

**Comment by mleanos** [comment]
@timelf123 Were you able to come up with a solution to your requirement?

**Comment by BillyCottrell** [comment]
I am kind of in the same situation I am using angular 9 for the website and loopback with express middleware for the backend. Thing is I have my own auth setup which works without issues, and I want to use Microsoft Graph to get booking information. So I don't need user information or anything else, except for the access tokens. Is there a way to be able to set this up? I have tried using the Microsoft Graph demo to see how things work, but they work with all the auth and user information that is not necessary in my case.
