### ISSUE TITLE
Passing response to callback causes timeout

### ISSUE THREAD

**Issue by timelf123** [AzureAD/passport-azure-ad#345]
When I attempt to pass `res` to the post method, my callback just hangs indefinitely
```
    app.post('/api/auth/office365/callback', function(req, res, next) {
      passport.authenticate('azuread-openidconnect', {session: false, failureRedirect: loginPage, response: res})(req, res, next);
      }, users.authCallback);
```
```
{"name":"AzureAD: OIDC Passport Strategy","hostname":"DESKTOP-XYZ","pid":44816,"level":30,"msg":"We are sending the response_type:  code id_token","time":"2017-11-20T20:06:51.082Z","v":0}
{"name":"AzureAD: OIDC Passport Strategy","hostname":"DESKTOP-XYZ","pid":44816,"level":30,"msg":"We are sending the response_mode:  form_post","time":"2017-11-20T20:06:51.082Z","v":0}
GET /api/auth/office365 302 0 - 3.617 ms
POST /api/auth/office365/callback - - - - ms
```

If I comment out `res.clearCookie(cookie);` in this lib, all works as expected

**Comment by lovemaths** [comment]
@timelf123 What are your express version and passport-azure-ad version? I just merged a PR into the dev branch which is related to this. Could you please give it a try and see if it solves the problem?

**Comment by lovemaths** [comment]
@timelf123 do you have cookieparser middleware installed to your app?

**Comment by timelf123** [comment]
@lovemaths will check out the dev branch tomorrow, thank you. I do have cookieparser installed as a middleware. 
`express@4.16.2`
`passport-azure-ad@3.0.8`

**Comment by timelf123** [comment]
Dev branch solves this issue, thank you. When will it be merged to main?

**Comment by lovemaths** [comment]
@timelf123 We will do an official release early next week, and we will let you know. Thank you.

**Comment by lovemaths** [comment]
@timelf123 We just did a new release (v3.0.9), please check it out. Thanks.
