### ISSUE TITLE
TENANTNAME_REGEX in lib/constants is too restrictive

### ISSUE THREAD

**Issue by bdragos** [AzureAD/passport-azure-ad#349]
We should be able to identify the tenant using a custom domain defined on the tenant and not only the *.onmicrosoft.com. I quickly removed the restriction and the v2 endpoints correctly handle the custom domains. 

Currently using a custom domain fails validation with this message:
"level":30,"msg":"authentication failed due to: In passport.authenticate: invalid tenantIdOrName somedomain.com"

Changing the TENANTNAME_REGEX in lib/constants to something more permissive allows me to authenticate with the custom domain. 

Let me know if you need more details,
Thanks, 
Dragos

**Comment by lovemaths** [comment]
What pattern does your custom domain have? Could you please a couple of examples?

**Comment by lovemaths** [comment]
@bdragos Working on it, will keep you posted. Thanks.

**Comment by lovemaths** [comment]
@bdragos We just did a new release (v3.0.9) with the fix, please check it out. Thanks.

**Comment by bdragos** [comment]
Sorry for the late response, first day back to work.
I tried the 3.0.9 and everything works as expected, thank you for the quick
fix.

Thanks,
Dragos
