### ISSUE TITLE
authentication failed due to: In _validateResponse: We did not receive a token we know how to validate

### ISSUE THREAD

**Issue by kasirajans** [AzureAD/passport-azure-ad#352]
I'm getting below error .Please advice ..

{"name":"AzureAD: OIDC Passport Strategy","hostname":"<Mac Name>-iMac.local","pid":1227,"level":30,"msg":"authentication failed due to: In _validateResponse: We did not receive a token we know how to validate","time":"2018-01-13T01:42:49.107Z","v":0}

**Comment by lovemaths** [comment]
@kasirajans This is because we didn't find 'kid' or 'x5t' field in the header of the id_token so we don't know what is the key to validate the id_token. What is your config? Where is the id_token coming from? You can copy your id_token in https://jwt.io/ and see what is in the header.

**Comment by kasirajans** [comment]
Yep you are right ! I could see only below in the header .

{
  "typ": "JWT",
  "alg": "HS256"
}
