### ISSUE TITLE
Support passing tenant name or id in BearerStrategy

### ISSUE THREAD

**Issue by sauravmajumder-microsoft** [AzureAD/passport-azure-ad#354]
For supporting multiple tenant there is a way to pass tenant name or id in the authenticate call in the OIDC Strategy. But there is no way to do the same thing for the Bearer Strategy. It will be good to have the same thing in Bearer Strategy so that tenant specific issuer won't need to be provided during configuration.

**Comment by lovemaths** [comment]
@sauravmajumder-microsoft Just release v3.0.10 with this feature, please give it a try. Thanks.

**Comment by sauravmajumder89** [comment]
Thanks! I will definitely try that.
