### ISSUE TITLE
Looping between  authorization endpoint and Redirect URI

### ISSUE THREAD

**Issue by kasirajans** [AzureAD/passport-azure-ad#355]
When I execute passport-azure-ad strategy with below code .Its looping me between authorization endpoint and redirect URI.

router.get('/login', passport.authenticate('azuread-openidconnect'));

router.post('/openid/return', passport.authenticate('azuread-openidconnect'), (req, res) => {
    log.info('Got proifle info');
    res.send('got call back');
});

++++++Passport config++++++++++

passport.use(new AzureOIDCStrategy({
    //option for AzureAD
    identityMetadata: keys.azureAD.identityMetadata,
    clientID: keys.azureAD.clientID,
    tenantGUID: keys.azureAD.tenentID,
    responseType: 'code id_token',
    responseMode: 'form_post',
    // Required if we use http for redirectUrl
    allowHttpForRedirectUrl: true,
    redirectUrl: 'http://localhost:3000/auth/openid/return',
    clientSecret: keys.azureAD.clientSecret,
    passReqToCallback:'false',
     // Optional, 'error', 'warn' or 'info'
    loggingLevel:'info',
    session:'false',
    resourceURL:'https://graph.microsoft.com'
}, () => {
    //passport callback function
    console.log('passport call back fun called');
   
})
)

++++++Azure AD OIDC Passport Strategy logs +++++++++

{"name":"AzureAD: OIDC Passport Strategy","hostname":"My-iMac.local","pid":16197,"level":30,"msg":"metadataUrl is: https://login.microsoftonline.com/Mytenant.onmicrosoft.com/.well-known/openid-configuration?x-client-SKU=passport-azure-ad&x-client-Ver=3.0.9","time":"2018-01-22T01:57:24.880Z","v":0}
{"name":"AzureAD: OIDC Passport Strategy","hostname":"My-iMac.local","pid":16197,"level":30,"msg":"received the following items in params: {\"policy\":null,\"cachekey\":\"https://login.microsoftonline.com/Mytenant.onmicrosoft.com/.well-known/openid-configuration?x-client-SKU=passport-azure-ad&x-client-Ver=3.0.9\",\"metadata\":{\"url\":\"https://login.microsoftonline.com/Mytenant.onmicrosoft.com/.well-known/openid-configuration?x-client-SKU=passport-azure-ad&x-client-Ver=3.0.9\",\"metadata\":null,\"authtype\":\"oidc\"}}","time":"2018-01-22T01:57:24.880Z","v":0}
{"name":"AzureAD: OIDC Passport Strategy","hostname":"My-iMac.local","pid":16197,"level":30,"msg":"entering Strategy.prototype._flowInitializationHandler","time":"2018-01-22T01:57:24.880Z","v":0}
{"name":"AzureAD: OIDC Passport Strategy","hostname":"My-iMac.local","pid":16197,"level":30,"msg":"We are sending the response_type:  code id_token","time":"2018-01-22T01:57:24.880Z","v":0}
{"name":"AzureAD: OIDC Passport Strategy","hostname":"My-iMac.local","pid":16197,"level":30,"msg":"We are sending the response_mode:  form_post","time":"2018-01-22T01:57:24.881Z","v":0}
{"name":"AzureAD: OIDC Passport Strategy","hostname":"My-iMac.local","pid":16197,"level":30,"msg":"metadataUrl is: https://login.microsoftonline.com/Mytenant.onmicrosoft.com/.well-known/openid-configuration?x-client-SKU=passport-azure-ad&x-client-Ver=3.0.9","time":"2018-01-22T01:57:25.520Z","v":0}
{"name":"AzureAD: OIDC Passport Strategy","hostname":"My-iMac.local","pid":16197,"level":30,"msg":"received the following items in params: {\"policy\":null,\"cachekey\":\"https://login.microsoftonline.com/Mytenant.onmicrosoft.com/.well-known/openid-configuration?x-client-SKU=passport-azure-ad&x-client-Ver=3.0.9\",\"metadata\":{\"url\":\"https://login.microsoftonline.com/Mytenant.onmicrosoft.com/.well-known/openid-configuration?x-client-SKU=passport-azure-ad&x-client-Ver=3.0.9\",\"metadata\":null,\"authtype\":\"oidc\"}}","time":"2018-01-22T01:57:25.520Z","v":0}
{"name":"AzureAD: OIDC Passport Strategy","hostname":"My-iMac.local","pid":16197,"level":30,"msg":"entering Strategy.prototype._flowInitializationHandler","time":"2018-01-22T01:57:25.520Z","v":0}
{"name":"AzureAD: OIDC Passport Strategy","hostname":"My-iMac.local","pid":16197,"level":30,"msg":"We are sending the response_type:  code id_token","time":"2018-01-22T01:57:25.520Z","v":0}
{"name":"AzureAD: OIDC Passport Strategy","hostname":"My-iMac.local","pid":16197,"level":30,"msg":"We are sending the response_mode:  form_post","time":"2018-01-22T01:57:25.520Z","v":0}

**Comment by ErrorPro** [comment]
Its probably cuz you don't have bodyParser middleware. Just add  `app.use(bodyParser.urlencoded({ extended: true }));` before your passport js

**Comment by kasirajans** [comment]
THanks . It worked also added npm cookie-parser and app.use(cookieParser()) .
