### ISSUE TITLE
How to get information out of JWT

### ISSUE THREAD

**Issue by HofmT** [AzureAD/passport-azure-ad#362]
Hi,

I'm currenlty using _passport-azure-ad_ for my node application. I have an Azure Active Directory where there is a user that belongs to a group within AD. My question is: how can I check in my app to which group a user that authenticated belongs to? I want to make the access to my app dependable on the group membership.

I had a look at the payload of the JWT token but all I found was the name and the email of the user but nothing about a group membership. Am I missing something?

Thanks in advance.

**Comment by HofmT** [comment]
Solved the issue by myself. It obviously had nothing to do with passport.
For all of you interested in this:
You have to edit the manifest file of your registered application in the Azure portal to enable the transmission of groups within the JWT token. (see [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-token-and-claims) for more details)

Then you can access the groups within the application with the request object like this:
`req.user._json.groups`
Notice that this returns an array and not a single groupID.

Hope I was able to help somebody.

**Comment by timmyreilly** [comment]
I'm curious if this is the best approach... Is this vulnerable to a spoofing attack? Or is just grabbing the contents of the req sufficient for implementing a roles based system?
