### ISSUE TITLE
Stateless w/ Access Token and Refresh Token

### ISSUE THREAD

**Issue by MarkHerhold** [AzureAD/passport-azure-ad#363]
What's the appropriate strategy to manage an access and refresh token when using a stateless (cookie) approach?

I'm thinking that one approach would be to create a new cookie via the `validate` callback (with signature `req, iss, sub, profile, accessToken, refreshToken, done`) and create a new cookie, then redirect my user to the home page. Does this approach sound correct?

When a user makes a request to the backend, I would decrypt the cookie, use the refresh token to refresh the access token (when needed). When the refresh token expires, I would clear the cookie, forcing users to login again.

## Setup Info:

- Node.js 8.9.4
- Using the OIDCStrategy
- `passReqToCallback` set to `true`
- `useCookieInsteadOfSession` set to `true`
- `cookieEncryptionKeys` are provided
- scope `'profile', 'offline_access', 'Mail.Send'`

**Comment by lovemaths** [comment]
@MarkHerhold I think this will work as long as the cookie has enough room for access token and refresh token.
