### ISSUE TITLE
Metadata caching in Bearer Strategy breaks and cannot be recovered if request fails

### ISSUE THREAD

**Issue by raiss** [AzureAD/passport-azure-ad#365]
# Issue
When there is a connection issue (e.g. due to proxy/network issue), fetching metadata fails and throw the following error and fails the request (as expected)
> In loadMetadata: Unable to fetch `metadata'
However, the subsequent requests hangs and never gets processed. They also don't throw any error and don't time out. So if one request to fetch metadata fails, it will never recover unless restarting the node process (to get rid of the cache)

# Reproduce
* [it is best to start with modifying the ttl and max for the cache-manager so you can experiment with turning connection off and back on to see the impact](https://github.com/AzureAD/passport-azure-ad/blob/b60459969d5d0973fdf9e24ced82c23a6b9fcf5c/lib/bearerstrategy.js#L41)
* disconnect the internet so the request to https://login.microsoftonline.com/7{tenantID}/v2.0/.well-known/openid-configuration fails
* send a request to an protected end point (which has the bearer strategy in place). This should return unauthorised 
* send the second request to the same end point. The request hangs and the nodejs doesn't throw any error

# Potential Solution
The appropriate signal needs to be sent to Cache Manager to let it know that there was a failour so it can clear itself. To do it the cacheCallback(fetchMetadataError) can be called. 
i.e. T[his bit of code can be modified ](https://github.com/AzureAD/passport-azure-ad/blob/b60459969d5d0973fdf9e24ced82c23a6b9fcf5c/lib/bearerstrategy.js#L540)
```js
Strategy.prototype.loadMetadata = function(params, next) {
  const self = this;
  var metadata = new Metadata(params.metadataURL, 'oidc', self._options);

  // fetch metadata
  return memoryCache.wrap(params.cacheKey, (cacheCallback) => {
    metadata.fetch((fetchMetadataError) => {
      if (fetchMetadataError) {
        cacheCallback(fetchMetadataError) // <<< ADDING THIS LINE WILL FIX THE ISSUE!
        return self.failWithLog('In loadMetadata: Unable to fetch metadata');

      }
      return cacheCallback(null, metadata);
    }, () => {console.log('find the buggg....... ')});
  }, { ttl }, next);
};
```

lib versions:

    passport: "0.3.2",
    passport-azure-ad: "3.0.10",

**Comment by lovemaths** [comment]
@raiss Fix is now available in 3.0.11, please check it out. Thanks.
