### ISSUE TITLE
Pkginfo dependency failing when bundled with webpack

### ISSUE THREAD

**Issue by cidbeltran** [AzureAD/passport-azure-ad#369]
**Version: 3.0.10**

Running unbundled works fine. After bundling i keep getting an error: Could not find package.json up from 457. Where 457 is the id of pkginfo webpack assigns. Seems pkginfo depending on the id of the current module to derive the given path causes the issue. 

A similar issue was brought up in meteorjs: https://github.com/meteor/meteor/issues/6313

Replacing it's usage (getLibraryVersion() in addutils.js) with 'return require('../package.json').version;' fixes this issue for me.

**Comment by lovemaths** [comment]
@cidbeltran Removed the dependency on pkginfo. The change is now in dev branch. Will ship with version 3.0.12. Thanks.
