### ISSUE TITLE
Cannot redeem authorization code

### ISSUE THREAD

**Issue by nanli1022** [AzureAD/passport-azure-ad#374]
Hi, I downloaded the sample code of Azure B2C for Nodejs Web APP but failed to run it successfully. 
Here's my trace:
```
token is decoded successfully
working on key
PEMkey is generated
claims are received
entering Strategy.prototype._authCodeFlowHandler
In _getAccessTokenBySecretOrAssertion: we are using client secret
authentication failed due to: In _authCodeFlowHandler: failed to redeem authorization code
```

From the network of browser, I can see that the id_token has been sent back successfully. In the audit log of azure b2c user, I can also see the following logs:
```
Activity
Date : 3/26/2018, 10:59:21 PM
Name : Issue an id_token to the application
CorrelationId : cbaa78f4-6f04-4ab6-8081-4xxxxxxxxx
Category : B2C
Activity Status
Status : Success
Reason : N/A
```
Please advise. Thanks!

**Comment by lovemaths** [comment]
@nanli1022 Add `loggingNoPII: false` to your config of OIDCStrategy, you will see more details why the authorization code is rejected.  (`loggingNoPII` means not logging anything related to personal identification information, turning it to false will give you the full detail of the error)

```
passport.use(new OIDCStrategy({
    ...
    loggingNoPII: false    // <==== add this options
  }, function(...) {
    ...
});
```

**Comment by winamp** [comment]
Hi @lovemaths, I'm having same issue here with mode detailed log msg:
```
{
  "name": "AzureAD: OIDC Passport Strategy",
  "hostname": "99682cc8279a",
  "pid": 1,
  "level": 30,
  "msg": "authentication failed due to: In _authCodeFlowHandler: failed to redeem authorization code: {\"statusCode\":400,\"data\":\"{\\\"error\\\":\\\"invalid_request\\\",\\\"error_description\\\":\\\"AADB2C90084: Public clients should not send a client_secret when redeeming a publicly acquired grant.\\\\r\\\\nCorrelation ID: 77e23092-66a0-4cc6-b683-bd7c29f63d99\\\\r\\\\nTimestamp: 2018-04-16 23:55:34Z\\\\r\\\\n\\\"}\"}",
  "time": "2018-04-16T23:55:34.234Z",
  "v": 0
}`

**Comment by eduardomourar** [comment]
The only way I could find to work was by making `responseType: 'id_token'`

**Comment by nanli1022** [comment]
The reason why I got this error is because I got a wrong client secret.
Maybe you can re-generate client secret and try again:)

**Comment by Murthy582** [comment]
In my case client secret has expired. As @nanli1022 said, I just regenerated and replaced it. It started working again.

**Comment by cyberf4n** [comment]
> The only way I could find to work was by making `responseType: 'id_token'`

you saved me, thanks a lot man

**Comment by pushkurella** [comment]
Yes when the client secret is expired or incorrect we get that "failed to redeem authorization code"

**Comment by pkanher617** [comment]
Appears to be solved, closing.
