### ISSUE TITLE
Passport issues when using with Kubernetes

### ISSUE THREAD

**Issue by HofmT** [AzureAD/passport-azure-ad#381]
Dear all,

I have encountered an issue when hosting an application secured by passport AD in a larger replicaset than 1.
My app consists of a very simple server.js that basically looks the same like the example application for passport-azure-ad provided by the [Getting Started examples.](https://github.com/AzureADQuickStarts/WebApp-OpenIDConnect-NodeJS). On top of that I define two further custom routes:

- app.use('/', ensureAuthenticated, express.static('dist')); This route hosts my Vue.js SPA. The dist directory consists of a single html that requests its js and css files from the same directory.
- app.get('/loginpage', function(req,res){...}: This is the route to the login page which is completely independent from the SPA.

The server is deployed inside a Kubernetes cluster which replicated three pods of this server. In this environment I was always successfully directed to the loginpage. However after logging in, I sometimes got redirected to loginpage again. When repeating the login process it either happened that I got once again redirected to the login page or that I got redirected to the root ('/') index page where just a blank page would be displayed. The reason of the blank page was that the browser complained about two html files that were returned. I had besides my index.html also the loginpage.html loaded which the browser did not expect (It only expcts .js or .css files but not another html file).

The error did not occur when I reduced the amount of the replicas to 1.
Does anyone have an idea what misconfiguration I have? 

Now, I'm aware that there is ADAL.js library which is specifically suited for SPA however, I did not want to provide the full client interface to each user on the Internet without prior authenticating that's why I use a nodejs express server that hosts both my loginpage and my static SPA files secured by the passport-azure-ad. If this is bad practice I'm happy to learn about new approaches

If you require more information, I'm happy to share it with you.
Thank you for each input!

**Comment by LaunaKay** [comment]
Not entirely sure if it's the same issue but we had something similar with
multiple replicas using Docker swarm. We fixed it by using sticky sessions
in Traefik. The issue was being (re)directed across multiple replicas
during the auth process which meant losing the session cookies that are
set, used and /or removed. We have a different stack but maybe this will
give you something to consider.

**Comment by HofmT** [comment]
Yes, thank you for your hint. This might be the case. I will have to check that.
