### ISSUE TITLE
Support when accessing a German Office 365 tenant

### ISSUE THREAD

**Issue by kidGodzilla** [AzureAD/passport-azure-ad#395]
I was wondering if there is an example or any documentation (I am having trouble locating it) related to using this to access a German Office 365 / Azure AD tenant. They seem to be operated in a separate facility by a local German provider, and the default integration doesn't seem to work.

We've been using this for quite some time but it inexplicably fails with very little debugging information.

It seems to authenticate without any issues after redirecting to the .de variant of the Microsoft login URL. Then, the response back to our servers is POST /token vs. GET /token, which fails.

(Feel free to toss me to Microsoft's support, or recommend next steps. Just curious if anyone has worked with this issue before).

**Comment by pkanher617** [comment]
Closing this for now. If this issue wasn't resolved, please open a new issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose) and we can help point you in the right direction.
