### ISSUE TITLE
Can I use this get token without popup user login screen ?

### ISSUE THREAD

**Issue by bluedusk** [AzureAD/passport-azure-ad#397]
Hi,
I need to write a backend app to read & write to a mailbox.  Can I use this library to get token from graph without the need of user login ?

**Comment by pkanher617** [comment]
Yes, this library should allow you to use backend APIs to fetch tokens for a server-side application without interaction. Have you taken a look at the [`msal-node`](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node) library? This should support the scenarios that you need. If it doesn't please open a new issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose).
