### ISSUE TITLE
README for verify function does not match implementation

### ISSUE THREAD

**Issue by rocketraman** [AzureAD/passport-azure-ad#398]
The README states:

> If you set passReqToCallback option to false, you can use one of the following signatures for the verify callback

and one of the signatures listed is:

```
  function(iss, sub, profile, access_token, refresh_token, done)
```

However, from the implementation it looks like only this signature is supported:

```
function(profile, done)
```

Same for the `passReqToCallback` true option.

See https://github.com/AzureAD/passport-azure-ad/blob/master/lib/bearerstrategy.js#L358

**Comment by rocketraman** [comment]
My mistake: verify callback is only documented that way for the `OIDCStrategy`. Is there a way to get the access token using the `BearerStrategy`?

**Comment by pkanher617** [comment]
@rocketraman The `OIDCStrategy` is meant to acquire a token if a user is not logged in, while the `BearerStrategy` is meant to validate access tokens from the `Authorization` header or body of the request coming into the passport app. If you still have issues getting an access token using the `OIDCStrategy` please open a new issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose).
