### ISSUE TITLE
Can i use this somehow with azure functions?

### ISSUE THREAD

**Issue by pstepnowski** [AzureAD/passport-azure-ad#404]
I tried it with express and working well, but is there any options/hacks to use it with azure functions?

**Comment by pkanher617** [comment]
@pstepnowski This is a passport library, and passport is built to work with express, so there is no support for other frameworks. However we are working on adding middleware functionality to the msal-node library, which you can find [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). Closing for now, please post in the [discussions channel](https://github.com/AzureAD/microsoft-authentication-library-for-js/discussions) if you have any further questions.

**Comment by derisen** [comment]
@pstepnowski @pkanher617 there's a 3rd party library, [azure-function-express](https://www.npmjs.com/package/azure-function-express) that converts your express code. You can see how its used in [this sample](https://github.com/Azure-Samples/ms-identity-nodejs-webapi-azurefunctions). Bear in mind this is more of a hack and doesn't support v3 functions.
