### ISSUE TITLE
adfs axample?

### ISSUE THREAD

**Issue by mosharov** [AzureAD/passport-azure-ad#406]
i see than library support adfs, but i can't see any examples...
I replaced some props, but got errors..
Maybe somebody will write required props with example values for adfs auth... thx/

**Comment by oising** [comment]
Came here to post the same thing -- how is this configured with ADFS -- just to reduce the amount of work for you guys, let's say ADFS 4.x with OpenID Connect  implicit flow

**Comment by poke** [comment]
For those looking for bearer authentication to protect an API with a JWT that was issued by a local ADFS, this is my setup:

```js
const bearerOptions = {
  // metadata endpoint for the local ADFS
  identityMetadata: 'https://adfs.example.com/adfs/.well-known/openid-configuration',

  // issuer address (`access_token_issuer` property in the metadata)
  issuer: 'http://adfs.example.com/adfs/services/trust',
  validateIssuer: true,

  // client id and token audience (“Relying Party Identifier“ from the “Web API” in the ADFS application group)
  clientID: 'https://api.example.com',
};

passport.use(new BearerStrategy(bearerOptions,
  function(token, done) {
    console.log('Received the following claims in the token:', token);
    return done(null, token);
  }
));
```

**Comment by pkanher617** [comment]
Closing this for now, if you are still having issues please open a new issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). This should also be supported in the new version of msal-node. We are also working on an update of the passport middleware library which will include this use case. You can track the progress of the project [here](https://github.com/AzureAD/microsoft-authentication-library-for-js).
