### ISSUE TITLE
authentication failed due to: connect ETIMEDOUT

### ISSUE THREAD

**Issue by nonongodup** [AzureAD/passport-azure-ad#417]
I am using node behind company proxy. It works well with localhost but get this error when deployed to PCF. in CF log, i get authentication failed due to: connect ETIMEDOUT. And 502 bad gateway-Registered endpoint failed to handle the request in UI. Does anyone have come up with same issue?

**Comment by cvsnpraveen** [comment]
I am also facing the same issue, could you help me, how did you resoled it
