### ISSUE TITLE
Remove Ursa dependency

### ISSUE THREAD

**Issue by omerlh** [AzureAD/passport-azure-ad#42]
Hey
As documented [here](https://azure.microsoft.com/en-us/documentation/articles/nodejs-use-node-modules-azure-apps/), Azure WebApp not supporting right now native modules installation. 
I will be great if you try to remove the ursa module, so we can easily use this module within azure web app.
Thanks,
Omer

**Comment by romiem** [comment]
+1
This is proving a showstopper for me.

**Comment by omerlh** [comment]
This should be very easy, instead of using ursa for creating the public key, it could be done like in this [library](https://github.com/dei79/node-azure-ad-jwt/blob/master/lib/azure-ad-validation-manager.js). Maybe it less secure, I am not sure what is the difference between the methods.

**Comment by brandwe** [comment]
I'm on it. This has been a problem with PCs when we moved to the latest version. I'm looking at alternatives now. Security and supportability is the most important concerns.

**Comment by brandwe** [comment]
Offending code is here: https://github.com/AzureAD/passport-azure-ad/blob/master/lib/passport-azure-ad/metadata.js#L210

**Comment by brandwe** [comment]
I've requested to use his fix here: https://github.com/dei79/node-azure-ad-jwt/issues/3

Unfortunately I can't just depend on the library as we'd need to do bug fixes, etc. and maintain the code.

**Comment by omerlh** [comment]
Great :+1:  Waiting for it...

**Comment by brandwe** [comment]
I have decided since this only requires generating the PEM to do so myself. I have a pull request out for this here: https://github.com/AzureAD/passport-azure-ad/pull/43

**Comment by omerlh** [comment]
Great. Waiting for merge and new version…

**Comment by brandwe** [comment]
Done and npm 1.1.1 published.

**Comment by omerlh** [comment]
Great. Thank you!
