### ISSUE TITLE
External Users Failing Auth

### ISSUE THREAD

**Issue by alimpaecher** [AzureAD/passport-azure-ad#421]
Currently I am unable to allow users with personal accounts, or accounts that are "external" to authenticate. 

> AADSTS50020: User account 'xxx@xxx' from identity provider 'live.com' does not exist in tenant 'xxx' and cannot access the application 'xxx'(xxx) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

We moved over from v1.0 to v2.0 to handle this exact scenario. Also I made the following changes to our manifest:
`"accessTokenAcceptedVersion": 2,`
and
`"signInAudience": "AzureADandPersonalMicrosoftAccount"`

Also I set the identify meta data to hit the v2.0 endpoint:
`identityMetadata: 'https://login.microsoftonline.com/xxx/v2.0/.well-known/openid-configuration',`

I've also noticed that while my id_token returns a v2.0 token. The access token I get is a v1.0. I have a suspicion that that might be a similar error.

Does anyone know why personal accounts are being blocked, despite the actions I've listed above?

**Comment by pkanher617** [comment]
@alimpaecher The [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node) library should be able to fulfill your authentication scenario. If you are still unclear or have more questions you can open a new [issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues) or [discussion](https://github.com/AzureAD/microsoft-authentication-library-for-js/discussions).
