### ISSUE TITLE
Dynamic Scopes

### ISSUE THREAD

**Issue by oehm-smith** [AzureAD/passport-azure-ad#430]
Is there a way to implement Dynamic Scopes directly in Passport-Azure-Ad?

I am using the TSED framework (https://tsed.io) that has an annotation I can specify scopes on the server REST endpoints.  You can see this and my current attempt at implementing AzureAD Auth at https://github.com/TypedProject/tsed-example-passport-azure-ad/pull/1.

So far all is going well but dynamic scopes as per the annotation like this:

    @Get("/hello-auth")
    @OAuthBearer({"scopes": ["app.special.scope"]})
    helloAuth() {
        return {text: "Authorised hello"};
    }

Are not yet operational.  Because I don't know how.  My understanding of passport-azure-ad is that it will only work with the bearer token and not pick up explicit scopes provided.

I was thinking that perhaps I could use `msal.js / acquireTokenSilent()`.  This would return a token (I'm hoping unless it barfs on not having a cached idToken).  And then I could somehow route this back through passport.

I just need advice on the best way to do this.  My suggested solution seems quite convoluted and what it solves seems like a common use case.

Does anyone have any advice?  Perhaps I have missed something obvious.

----

Just to confirm what is happening, in the `decorators / OAuthBearer.ts` (which is the annotation on the endpoint), it is calling `passport.authenticate` and passing the value of the annotation.  So this annotation is available to callback function.

**Comment by oehm-smith** [comment]
I can't see that you can call `passport.authenticate()` again as you don't have the request, response and next arguments in the callback function.

**Comment by oehm-smith** [comment]
I created a stackoverflow question for this - https://stackoverflow.com/questions/56698377/passport-azure-ad-msal-js-and-dynamic-scopes

I commented:

I worked out what I'll do.  I'll send a 'preflight' request to get the scopes to pass to `MSAL.js / acquireTokenSilent` method.  That will auth the person against the scope and they'll have a bearer token to pass to the API (with `passport-azure-ad` doing its thing).  I'm yet to implement that.

**Comment by pkanher617** [comment]
@oehm-smith We are working on a new version of the passport library, and we will definitely cover this scenario when that version is released. We are still in the design phase but please watch the [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js#roadmap) for more information.

**Comment by oehm-smith** [comment]
Cool. I'm glad to see that the Passport project has been re-started.
