### ISSUE TITLE
How to access passport fail messages eg. "token is not found"

### ISSUE THREAD

**Issue by oehm-smith** [AzureAD/passport-azure-ad#431]
If a token is not sent then this error can be seen in the server log.  The client receives a generic "401 Unauthorized" error.  How can I capture error messages so they can be better acted upon?

**Comment by pkanher617** [comment]
We are working on a new version of the passport library, and we will be updating the error messaging. We are still in the design phase but please watch the [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js#roadmap) for more information.
