### ISSUE TITLE
Policy checker is wrong in oidcstrategy

### ISSUE THREAD

**Issue by qaiserdwp** [AzureAD/passport-azure-ad#439]
In oidcstrategy.js policyChecker for B2C is checking for policy in path. It should check for policy name in query parameter. 

```return u.pathname && _.includes(u.pathname, policy.toLowerCase());```
It used to be
```return u.query && u.query.p && (policy.toLowerCase() === u.query.p.toLowerCase());```
Can we update this to check in both query or path?

**Comment by rodrigo-martinezd** [comment]
I have recently this problem. Also in u.pathname are excluded the query params so the policyChecker always fails.

**Comment by sjclemmy** [comment]
Yeah it should be `u.path` or `u.query` not `u.pathname`

**Comment by DarylThayil** [comment]
resolved in 4.2.1
