### ISSUE TITLE
callback not working with newest xml-crypto release

### ISSUE THREAD

**Issue by davideickhoff** [AzureAD/passport-azure-ad#44]
we noticed that the dependencies in the package.json do not point to specific versions of the external libs.. this is dangerous and broke our system

please update the dependencies to use specific versions. On our site it works with the following changes
https://github.com/audibene-em/passport-azure-ad

**Comment by brandwe** [comment]
Yes but it's a struggle as some systems won't have the problem and need additional features. It's hard to lock down on a lot of these for bug fix reasons - node libs are pretty lax on semantic versioning. I will take your xml change though if you want to push it.
