### ISSUE TITLE
Unable to get the Callback from BearerStrategy

### ISSUE THREAD

**Issue by BelalKazmi** [AzureAD/passport-azure-ad#443]
I am using **Mult-Tenant** for the Node Application and so unable to validate the token which is called on the fly.
In my routes I am using something like this :

`router.get("/getData",authenticate, (req, res, next) => {`
- **getData** is the GET METHOD route 
- **authenticate** is the user-defined method to authenticate using passport 

In my user-defined method **authenticate** , I have the following code :
```
var passport = require("passport");
var BearerStrategy = require('passport-azure-ad').BearerStrategy;
var jwtDecode = require('jwt-decode');
module.exports = function authenticate(req) {
  const authorization=req.headers.authorization;
  const  decodedToken = jwtDecode(authorization);
  const tenantId=decodedToken.tid;
  const clientId=decodedToken.aud;
  var options = {
    identityMetadata: `https://login.microsoftonline.com/${tenantId}/v2.0/.well-known/openid-configuration`,
    clientID: clientId,
    validateIssuer: false,
    audience:"https://graph.windows.net",
    loggingLevel: 'warn',
    loggingNoPII: false
  };
   var bearerStrategy = new BearerStrategy(options,function (token, done) {
    done(null, {}, token);
  });
  passport.use(bearerStrategy);
  return(passport.authenticate('oauth-bearer', {session: false}));
}
```

Hence, in ideal conditions (as per me) , it should call the GET Method and then go inside Authenticate Method and if the token is valid, it should proceed with the next steps of that method.
And if the Authenticate Method gives _Unauthorized_ ,then we need to not go ahead with the GET Method steps and return Unauthorized.

### The CallBack of **_done_** is not being called and going in infinite loop.

PS: Passport is already initialized in the app.js
`app.use(passport.initialize());`

**Comment by pkanher617** [comment]
@BelalKazmi Have you taken a look at the [samples](https://github.com/AzureAD/passport-azure-ad#7-samples-and-documentation)? The bearer strategy should take care of extracting and decoding the token, so you can just use `passport.authenticate('oauth-bearer')` directly in the `router.get` method.

**Comment by sameerag** [comment]
Closing as no response from the author. 

Note: We are currently in the design phase of a new version of this library, which can be tracked [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9). The timeline for the new library will be uploaded to our [MSAL JS repo](https://github.com/AzureAD/microsoft-authentication-library-for-js).
