### ISSUE TITLE
Junk in the state attribute

### ISSUE THREAD

**Issue by Kelbie** [AzureAD/passport-azure-ad#444]
Hi I'm new so sorry if this is obvious.

When trying to dynamically redirect the user after login is complete I try take the value stored in state but its got other information that I don't want. Is this normal, whats the common way to handle this?

Set the redirect:

    function(req, res, next) {
      let redirect = req.query.redirect;
      passport.authenticate('azuread-openidconnect', 
        { 
          response: res,
          resourceURL: config.resourceURL,
          customState: redirect,
          failureRedirect: '/',
        }
      )(req, res, next);
    },

In the `/auth/openid/return` route `req.body.state` returns `CUSTOMA2FjUF-UokhWwA7Q0s9SocNCnRB6W3Bd<redirect>` but what is all this other stuff `CUSTOMA2FjUF-UokhWwA7Q0s9SocNCnRB6W3Bd`?

**Comment by marrinn** [comment]
I have the same issue. This was working previously but now seems to add the prefix in line 1393 of oidcstrategy.js and is never removed: 
`// add state/nonce/policy/timeStamp tuple to session or cookie
  let state = params.state = oauthConfig.customState ? ('CUSTOM' + aadutils.uid(32) + oauthConfig.customState) : aadutils.uid(32);`

I can workaround the issue using the code at line 709 of oidcstrategy.js (below) but this isn't the expected behaviour.
`    if (source.state && source.state.length >= 38) {
      // the random generated state always has 32 characters. This state is longer than 32
      // so it must be a custom state. We added 'CUSTOM' prefix and a random 32 byte long
      // string in front of the original custom state, now we change it back.
      if (!source.state.startsWith('CUSTOM'))
        return next(new Error(`In collectInfoFromReq: invalid custom state ${state}\`));

      source.state = source.state.substring(38);
    }
  }`

Any idea what could cause this?

**Comment by marrinn** [comment]
> I have the same issue. This was working previously but now seems to add the prefix in line 1393 of oidcstrategy.js and is never removed:
> `// add state/nonce/policy/timeStamp tuple to session or cookie let state = params.state = oauthConfig.customState ? ('CUSTOM' + aadutils.uid(32) + oauthConfig.customState) : aadutils.uid(32);`
> 
> I can workaround the issue using the code at line 709 of oidcstrategy.js (below) but this isn't the expected behaviour.
> ` if (source.state && source.state.length >= 38) { // the random generated state always has 32 characters. This state is longer than 32 // so it must be a custom state. We added 'CUSTOM' prefix and a random 32 byte long // string in front of the original custom state, now we change it back. if (!source.state.startsWith('CUSTOM')) return next(new Error(`In collectInfoFromReq: invalid custom state ${state}`));
> 
> ```
>   source.state = source.state.substring(38);
> }
> ```
> 
> }`
> 
> Any idea what could cause this?

Ok so I've worked out what's going on here. Attempting to access the state value before the authenticate call in the return will result in the CUSTOM prefix still being present. It's stripped out after the Authenticate call. I needed to do this to use a fully generic return route passing the provider name. 

`app.post('/auth/openid/return', function(req,res,next) {   

    let authProviderDecoded = JSON.parse(Buffer.from(req.body.state,'base64').toString('ascii'));
    passport.authenticate(authProviderDecoded.providerName, { 
        failureRedirect: '/#/login', 
        failureFlash: true 
    })(req,res,next);
    }, function (req, res) {        
        res.redirect(`/#/login/login-oidc?authProvider=${req.body.state}&token=${req.body.id_token}`);
    });`

The workaround is to strip out the prefix before the authenticate call or use this solution [https://dev.to/dangolant/dynamic-auth-redirects-with-passportjs-380g](url)

**Comment by pkanher617** [comment]
We are working on a new version of the passport library, and we will be making the asynchronous code easier to handle. We are still in the design phase but please watch the [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js#roadmap) for more information.
