### ISSUE TITLE
Authentication fails when using Chrome w/ flag "same-site-by-default-cookies" and OIDCStrategy useCookieInsteadOfSession=true

### ISSUE THREAD

**Issue by sebrenna** [AzureAD/passport-azure-ad#448]
I have my OIDCStrategy configured like so:

```js
passport.use(
    new OIDCStrategy({
        // other config properties
        cookieEncryptionKeys: ...,
        passReqToCallback: true,
        responseMode: 'form_post',
        responseType: 'code',
        useCookieInsteadOfSession: true,
        validateIssuer: true,
        // ...
    }, function (...) {
        // ....
    }));
```

This works great in my current version of Chrome. (77.0.3865.120) However, if I enable the experiment "SameSite by default cookies", the auth workflow fails, as no cookies are sent along with the authReturn redirect.

The heart of this issue is that (I believe) passport-azure-ad is setting cookies with no value for SameSite set. With this experiment enabled, this will now result in cookies having SameSite=**Lax** by default, whereas in the past they'd be SameSite=**None**.

This will soon be a problem for all Chrome users, as this feature will be enabled by default in Chrome 80, which should be out in early February 2020. Per this article: https://www.chromestatus.com/feature/5088147346030592

**Comment by DarylThayil** [comment]
Actively looking into resolving this, thanks for patience

**Comment by DarylThayil** [comment]
@sebrenna  can you confirm it is the "passport-aad" cookie that is being returned with no same-site?

**Comment by DarylThayil** [comment]
4.2 has been released with this, please try it out and let me know if it resolves your issue.
