### ISSUE TITLE
How to validate token was issued by Microsoft

### ISSUE THREAD

**Issue by kas84** [AzureAD/passport-azure-ad#449]
I want to allow any tenant to single sign on in my application, but if don’t validate issuer (I’d like it to be any), how do I validate the token was issued by Microsoft?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sameerag** [comment]
@kas84 This may help you - [guidance](https://thomaslevesque.com/2018/12/24/multitenant-azure-ad-issuer-validation-in-asp-net-core/), same thing should be applicable for passport-azure-ad
