### ISSUE TITLE
Getting ETIMEDOUT Error, sometimes on a day while working on a corporate network

### ISSUE THREAD

**Issue by cvsnpraveen** [AzureAD/passport-azure-ad#455]
Working on Passport-Azure-Ad with OIDCStrategy v2 on a corporate network, getting ETIMEDOUT error sometime a day, not sure with the reason.

It is working fine in local but in server all of sudden around 10 mins I am getting the issue

**Comment by bburhans** [comment]
Without logs, code, or debugging information, there's not a lot we can offer toward a cause or a fix. That said, timeouts in express are often the result of a missing call to `next()`, or if using async handlers/middleware, perhaps a promise that's not being fulfilled somewhere.

**Comment by marcelvossmint** [comment]
@cvsnpraveen you find out anything?

**Comment by pkanher617** [comment]
closing as there is no response. Please open a new issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues) if you are still having problems.
