### ISSUE TITLE
Add the ability to pass log instance in options

### ISSUE THREAD

**Issue by omerlh** [AzureAD/passport-azure-ad#46]
Hey
Currently the log always write to console, which is very annoying. Would be great if I could pass custom banyan logger so I could control to where your logs will be written, and on which level. I was thinking about something like that:
https://gist.github.com/omerlh/415ef7efceaa4787dc23
Thank you!
Omer

**Comment by jeffwilcox** [comment]
See also: https://github.com/AzureAD/passport-azure-ad/issues/72

**Comment by brandwe** [comment]
Fixed in #82

**Comment by jeffwilcox** [comment]
Thank you - excited to check this out!
