### ISSUE TITLE
response key in passport.authenticate config lacks documentation

### ISSUE THREAD

**Issue by bburhans** [AzureAD/passport-azure-ad#463]
[README.md](https://github.com/AzureAD/passport-azure-ad/blob/ee2ec66e8d1b393809f846547d36edb24a2fd2c8/README.md) specifies that a `resource` key is conditionally required, but nothing describes its API, and none of the usage examples mention it at all. I did find a couple snippets elsewhere that are calling `authenticate()` from ad hoc middleware instead of using it directly as middleware, which allows them access to the `res` argument and therefore they can pass `resource: res` in the `authenticate()` config.

Is this actually required, or automatically set when the return value of `authenticate()` is used as standalone express 4 middleware (as in the official examples), or something else? If required, how should it be used?

If its usage has changed over time, I'm specifically interested in version 4.2.1, which is `@latest` on npm but is not set as the `latest` release with GitHub.

**Comment by bburhans** [comment]
I just found a more [authoritative source](https://github.com/AzureAD/passport-azure-ad/issues/289#issuecomment-292672167): for cookie state/nonce instead of session state/nonce, wrap the `authenticate()` call in ad hoc middleware solely to pass the `response` key:

> wherever you use
> ```
> passport.authenticate('azuread-openidconnect', {...}),
> ```
> change it to
> ```
> function(req, res, next) {
>   passport.authenticate('azuread-openidconnect', { response: res, ... })(req, res, next);
> },
> ```

This is from almost three years ago; if this is still accurate, may I add it to the README and/or example scripts?

**Comment by jennyf19** [comment]
@bburhans we welcome any contributions. Thank you.

**Comment by pkanher617** [comment]
We are working on an overhaul for the passport library, and will make sure to include proper documentation around usage of the `passport.authenticate` API.
