### ISSUE TITLE
Default bunyan logger causing problem in my node logger

### ISSUE THREAD

**Issue by MsumanP** [AzureAD/passport-azure-ad#466]
I am getting this error in my winston logger. Is there any way to remove the bunyan logger ?
`{"error":{"errno":-5,"syscall":"write","code":"EIO"},"level":"error","message":"uncaughtException: EIO: i/o error, write\nError: EIO: i/o error, write\n    at writeSync (fs.js:573:3)\n    at SyncWriteStream._write (internal/fs/sync_write_stream.js:22:3)\n    at doWrite (_stream_writable.js:415:12)\n    at writeOrBuffer (_stream_writable.js:399:5)\n    at SyncWriteStream.Writable.write (_stream_writable.js:299:11)\n    at Logger._emit (/home/36861/newproduction/Billing-recon-Automation/backend/node/node_modules/bunyan/lib/bunyan.js:923:22)\n    at Logger.warn (/home/36861/newproduction/Billing-recon-Automation/backend/node/node_modules/bunyan/lib/bunyan.js:1045:24)\n    at new Strategy (/home/36861/newproduction/Billing-recon-Automation/backend/node/node_modules/passport-azure-ad/lib/bearerstrategy.js:259:9)\n    at Object.<anonymous> (/home/36861/newproduction/Billing-recon-Automation/backend/node/3001.js:52:32)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)","stack":"Error: EIO: i/o error, write\n    at writeSync (fs.js:573:3)\n    at SyncWriteStream._write (internal/fs/sync_write_stream.js:22:3)\n    at doWrite (_stream_writable.js:415:12)\n    at writeOrBuffer (_stream_writable.js:399:5)\n    at SyncWriteStream.Writable.write (_stream_writable.js:299:11)\n    at Logger._emit (/home/36861/newproduction/Billing-recon-Automation/backend/node/node_modules/bunyan/lib/bunyan.js:923:22)\n    at Logger.warn (/home/36861/newproduction/Billing-recon-Automation/backend/node/node_modules/bunyan/lib/bunyan.js:1045:24)\n    at new Strategy (/home/36861/newproduction/Billing-recon-Automation/backend/node/node_modules/passport-azure-ad/lib/bearerstrategy.js:259:9)\n    at Object.<anonymous> (/home/36861/newproduction/Billing-recon-Automation/backend/node/3001.js:52:32)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)","exception":true,"date":"Thu Jan 23 2020 13:24:05 GMT+0530 (India Standard Time)","process":{"pid":30066,"uid":1000,"gid":1000,"cwd":"/home/36861/newproduction/Billing-recon-Automation/backend/node","execPath":"/usr/bin/node","version":"v10.16.0","argv":["/usr/bin/node","/home/36861/newproduction/Billing-recon-Automation/backend/node/3001.js"],"memoryUsage":{"rss":51994624,"heapTotal":41197568,"heapUsed":23850200,"external":774775}},"os":{"loadavg":[19.25732421875,4.91015625,7.525390625],"uptime":30849534},"trace":[{"column":3,"file":"fs.js","function":"writeSync","line":573,"method":null,"native":false},{"column":3,"file":"internal/fs/sync_write_stream.js","function":"SyncWriteStream._write","line":22,"method":"_write","native":false},{"column":12,"file":"_stream_writable.js","function":"doWrite","line":415,"method":null,"native":false},{"column":5,"file":"_stream_writable.js","function":"writeOrBuffer","line":399,"method":null,"native":false},{"column":11,"file":"_stream_writable.js","function":"SyncWriteStream.Writable.write","line":299,"method":"write","native":false},{"column":22,"file":"/home/36861/newproduction/Billing-recon-Automation/backend/node/node_modules/bunyan/lib/bunyan.js","function":"Logger._emit","line":923,"method":"_emit","native":false},{"column":24,"file":"/home/36861/newproduction/Billing-recon-Automation/backend/node/node_modules/bunyan/lib/bunyan.js","function":"Logger.warn","line":1045,"method":"warn","native":false},{"column":9,"file":"/home/36861/newproduction/Billing-recon-Automation/backend/node/node_modules/passport-azure-ad/lib/bearerstrategy.js","function":"new Strategy","line":259,"method":null,"native":false},{"column":32,"file":"/home/36861/newproduction/Billing-recon-Automation/backend/node/3001.js","function":null,"line":52,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":776,"method":"_compile","native":false}]}
`

**Comment by jennyf19** [comment]
@DarylThayil your thoughts?

**Comment by MsumanP** [comment]
Any comments?

**Comment by jennyf19** [comment]
@DarylThayil

**Comment by DarylThayil** [comment]
Unfortunately this library is not under active development, we are however taking contributions and are willing to cut patches for fixes.

@MsumanP  is it possible you have time to contribute to this and optionally remove bunyan? Or find a way for this to more elegantly be handled?

In our long term plans we do have a plan to either refresh this library or create a new middleware, apologies for the delay.

**Comment by pkanher617** [comment]
Closing this for now, if you are still having issues please open a new issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). We are also working on an update of the passport middleware library which will update how the logger works. You can track the progress of the project [here](https://github.com/AzureAD/microsoft-authentication-library-for-js).
