### ISSUE TITLE
State param not returning value in Azure AD open id connect passport strategy

### ISSUE THREAD

**Issue by vineet-suri** [AzureAD/passport-azure-ad#468]
I am trying to authenticate users to the app using Azure AD open id connect passport strategy. As per documentation, if a state parameter is included in the request, the same value should appear in the response. I am trying to implement this by passing state in query parameters of login api and alternatively passing in the options object of passport strategy. But either ways, the state which was passed is not coming in the request object of callback api, rather a randomly generated value for state is coming. My use case is to pass the client_id of the auth client requesting access to the azure ad auth, and to sign jwt based on that in the callback api from AD. I am using NestJs as the backend Node framework. Below are the relevant code snippets: azure-ad.strategy.ts

```
import { Injectable, UnauthorizedException } from '@nestjs/common';
import { OIDCStrategy } from 'passport-azure-ad';
import { PassportStrategy } from '@nestjs/passport';
import { AuthService } from '../services/auth.service';

const options = {
    identityMetadata: process.env.AZUREAD_IDENTITY_METADATA,
    clientID: process.env.AZUREAD_AUTH_CLIENT_ID,
    responseType: 'id_token',
    responseMode: 'form_post',
    redirectUrl: process.env.AZUREAD_REDIRECT_URL,
    allowHttpForRedirectUrl: true,
    clientSecret: process.env.AZUREAD_AUTH_CLIENT_SECRET,
    validateIssuer: false,
    issuer: null,
    passReqToCallback: true,
    useCookieInsteadOfSession: true,
    cookieEncryptionKeys: [
        { key: '12345678901234567890123456789012', iv: '123456789012' },
        { key: 'abcdefghijklmnopqrstuvwxyzabcdef', iv: 'abcdefghijkl' },
    ],
    scope: ['profile', 'offline_access', 'https://graph.microsoft.com/mail.read'],
    loggingLevel: 'info',
    nonceLifetime: null,
    nonceMaxAmount: 5,
    clockSkew: null,
    state: 'app',
};

@Injectable()
export class AzureAdStrategy extends PassportStrategy(OIDCStrategy) {
    constructor(private readonly authService: AuthService) {
        super(options);
    }

    async validate(req, profile, done): Promise<any> {
        const user = await this.authService.validateUser(profile);
        if (!user) {
            throw new UnauthorizedException();
        }
        return user;
    }
}
```
azure-ad-login.controller.ts

```
@Controller('auth')
export class AzureADLoginController {
    constructor(
        private readonly userService: UsersService,
        private readonly authClientRepo: AuthClientRepository,
        private readonly jwtService: JwtService,
    ) {}

    @UseGuards(AuthGuard('azuread-openidconnect'))
    @Get('login')
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    async login(@Query('client_id') clientId: string, @Query('client_secret') clientSecret: string): Promise<void> {}

    @UseGuards(AuthGuard('azuread-openidconnect'))
    @Post('azure-ad-redirect')
    async returnUrl(@Request() req, @Query('state') state: string, @Response() resp): Promise<void> {
        ...
}
```
Please help by showing how to pass the state params properly in this scenario, so that i can retrieve them in callback api from AD.

**Comment by jennyf19** [comment]
@vineet-suri are you using `customState`: if you want to use a custom state value instead of a random generated one? https://github.com/AzureAD/passport-azure-ad#513-options-available-for-passportauthenticate
Can you provide a repro and directions on how to set it up?

cc: @jmprieur

**Comment by vineet-suri** [comment]
@jennyf19 yes, now I am using customState, and it is working fine. I could provide the required param by overriding authenticate function in PassportStartegy interface provide by framework (NestJs), and providing customState param in options of super.authenticate().
So, closing the issue.
