### ISSUE TITLE
getting error after successful authentication

### ISSUE THREAD

**Issue by rajeevp** [AzureAD/passport-azure-ad#471]
I see this error message in my console after token is decoded successfully.
"msg":"authentication failed due to: In _validateResponse: failed to generate PEM key due to: params.metadata.generateOidcPEM is not a function"

any idea, why this is failing?
I see the metadata.js is adding generateOidcPEM as prototype method, actually it should get it, am i missing something here?

Note: in oidcstrategy.js if i replace line number 824 from
"params.metadata = metadata"
with
params.metadata = Object.assign(params.metadata, metadata)

then it works, somehow metadata object is loosing its type (i.e. Metadata) after successful login

**Comment by rajeevp** [comment]
I added following code in oidcstrategy.js at line number: 818. just to check what it stores in cache
(metadata, next) => {
      console.log(metadata)
      memoryCache.get(params.cachekey)
      .then(result => console.log(result))
      return next(null, metadata)
    },

For the first time it gives me proper Metadata Object for subsequent class (when it fetches from cache) it give me plain 'object' (check __proto__) without any prototype methods

**Comment by kratker** [comment]
We have exactly the same problem. It was working fine before we migrated to a new App Service. Perhaps some sort of dependency breaks the functionality?

**Comment by rajeevp** [comment]
I am checking the version of cache-manager, comparing it with v1.0 flow both are same. Note: the v1.0 flow works exactly fine. 
the above code prints always Metadata as object type which is persisted in memory

**Comment by kratker** [comment]
I think this is caused by the recent update to cache-manager. There is an issue referencing passpor-azure-ad https://github.com/BryanDonovan/node-cache-manager/issues/132#issuecomment-581519588

**Comment by rajeevp** [comment]
Found in one of the issue description that it works with cache-manager@2.10.2 and it is.
Closing this issue because it is cache-manager issue not related to passport-azure-ad.
