### ISSUE TITLE
"invalid state received in the request" for SameSite: "Lax"

### ISSUE THREAD

**Issue by ryan-codingintrigue** [AzureAD/passport-azure-ad#477]
When using the following cookie configuration:

```js
resave: true,
saveUninitialized: false,
cookie: {
    secure: true,
    httpOnly: true,
    sameSite: "lax"
}
```

The OIDCStrategy returns the following error:

> authentication failed due to: In collectInfoFromReq: invalid state received in the request

We've narrowed this down to `sameSite: "lax"`.

I'm not sure what the library is doing with the request that makes this fail. The cookie is successfully sent with the request when using other providers (Google, Twitter, Facebook, etc.)

**Comment by pkanher617** [comment]
Closing as the linked PR was closed, resolved by setting SameSite="none".
