### ISSUE TITLE
OIDC B2C sample incorrectly marked as Archived project

### ISSUE THREAD

**Issue by cmedgile** [AzureAD/passport-azure-ad#479]
The b2c sample project is likely incorrectly archived 
https://github.com/AzureAD/passport-azure-ad#81-samples-for-openid-connect-strategy

This likely needs to be updated (also I could use assistance in getting it to work), the B2C library might be out of date or have another issue that prevents it from working with the directory.

**Comment by pkanher617** [comment]
We are working on an overhaul of the passport library and will be migrating it to our mono-repo [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). We will be creating a new set of samples for common scenarios including B2C. Closing for now.
