### ISSUE TITLE
B2C Federation: Unable to access Federation metadata

### ISSUE THREAD

**Issue by cmedgile** [AzureAD/passport-azure-ad#480]
I'm using [the following Microsoft sample][1] for Azure B2C on NodeJS and am receiving the following error:

    ERROR: AzureAD: Metadata Parser/59044 on DESKTOP1: cannot get AAD Federation metadata from endpoint you specified
    INFO: AzureAD: OIDC Passport Strategy/59044 on DESKTOP1: authentication failed due to: Cannot get AAD Federation metadata

I assume this is referring to the config.js/exports/creds/IdentityMetadata, however I **am able** to access both of the following B2C URLs directly.

 * https://TENANT.b2clogin.com/TENANT.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_TestUserFlowSignUp
 *  https://login.microsoftonline.com/TENANT.onmicrosoft.com/v2.0/.well-known/openid-configuration
 
**Question**

1. How can I debug the Passport's library failure to access FederationMetadata?  (fiddler didn't show any network IO)
2. Is it stored or cached somewhere? 
3. When and how is it used (for troubleshooting)?

Link to StackOverflow question
https://stackoverflow.com/q/60442145/12900015

  [1]: https://github.com/AzureADQuickStarts/B2C-WebApp-OpenIDConnect-NodeJS

**Comment by cmedgile** [comment]
Update:

I tested changing the Token compatibility settings to tfp and the related (iss) claim to the uri that includes the tfp string in the URL.  No improvement.

**Comment by pkanher617** [comment]
@cmedgile If this is still an issue, please open another ticket [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues) with all of the information included here, and any other pertinent information. We are working on an overhaul of the passport library and will be migrating it to our mono-repo [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). We are only pushing security fixes for the current passport-azure-ad library. Closing for now.
