### ISSUE TITLE
Remove dependency on deprecated 'request' library

### ISSUE THREAD

**Issue by ghtaylor** [AzureAD/passport-azure-ad#490]
Is there any plan to remove passport-azure-ad away from using request? It has [recently been deprecated](https://github.com/request/request/issues/3142), and it would therefore be worth-while moving to another library.

**Comment by jennyf19** [comment]
@DarylThayil any comment on this?

**Comment by DevRCRun** [comment]
This may no longer be purely an enhancement, Snyk reports the following:

> Issues with no direct upgrade or patch:
>   ✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-AJV-584908] in ajv@6.12.0
>     introduced by passport-azure-ad@4.2.1 > request@2.88.2 > har-validator@5.1.3 > ajv@6.12.0
>   This issue was fixed in versions: 6.12.3

**Comment by pkanher617** [comment]
This library is in maintenance mode, and we are only making security fixes currently. We are currently in the design phase of a new version of this library, which can be tracked [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9). The timeline for the new library will be uploaded to our [msal js repo](https://github.com/AzureAD/microsoft-authentication-library-for-js). We will ensure that the new library is using up-to-date dependencies for the request/response and other features.
