### ISSUE TITLE
How to get the current loggedin user, token info and token expiry using an REST api.

### ISSUE THREAD

**Issue by anjiuidev** [AzureAD/passport-azure-ad#491]
Hi,

I am using the OIDC strategy to log in to the user with b2c policy. Login functionality is working great. Now I wanted to expose the current login user information as an API, how to do that also wanted to expose tokens in the API, so that my client app can use this data.

**Comment by jennyf19** [comment]
@anjiuidev you would you use the id_token, which is returned after the user signs in. You can parse the claims in the id_token and get information about the signed in user. The claims you request can be set in the Azure AD B2C portal.

**Comment by anjiuidev** [comment]
@jennyf19 Thanks for your response.
