### ISSUE TITLE
How to enable option to choose between different domain accounts of MS Azure while doing OAuth?

### ISSUE THREAD

**Issue by prashant-indexnine** [AzureAD/passport-azure-ad#492]
Hi,

We are using `OIDCStrategy`  with common URL `https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration`

Things are working as expected across the domains if not tried on the same browser.

But in case of the same browser, If a user with domain `domainone.com` logs into azure portal & his session is ongoing.

Now another user with `domaintwo.com` opens our web app clicks on the login button he is auto-redirected to `domainone.com` OAuth instead of giving choice to select his account `domaintwo.com`. in Microsoft authentication service.

Is there any flag in an `OIDCStrategy` configuration which enables the redirection UI to select from multiple accounts that are there on the browser. ( Irrespective of the current active session in browser ) ?

The version we are using: `passport-azure-ad: 4.0.0` & we have enabled `useCookieInsteadOfSession: true` 

Any help appreciated.

Thanks

**Comment by jennyf19** [comment]
@prashant-indexnine can you pass in a prompt, like `login` or `select_account`?

**Comment by prashant-indexnine** [comment]
Hi, @jennyf19 thanks for the response. I added both options for prompt but still not getting UI widget to choose the account. It directly takes into the account of azure portal login that the browser already has.

``` javascript
passport.use( new OIDCStrategy( {
// Other additional settings of passport
// ...
// ...
prompt: 'select_account'
},function ( req: any, iss: any, sub: any, profile: any, accessToken: any, refreshToken: any, params: any, done: any ) {
// Handling of callback on redirection
} ) );
```

**Comment by shokai** [comment]
@prashant-indexnine

The `prompt` option should not be set when you create the OIDCStrategy.
it should be set when you register the passport.authenticate with the router.

```js
app.get('/login', passport.authenticate('azuread-openidconnect', { prompt: 'select_account' }))
```

the document is here.
https://github.com/AzureAD/passport-azure-ad#413-options-available-for-passportauthenticate

I was able to learn about this option and solve the exact same problem thanks to this issue. Thank you for opening this issue.

**Comment by pkanher617** [comment]
Appears to be resolved by the latest comment. We are currently in the design phase of a new version of this library, which can be tracked [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9). The timeline for the new library will be uploaded to our [MSAL JS repo](https://github.com/AzureAD/microsoft-authentication-library-for-js). 

@prashant-indexnine If you are still having problems please open a new issue in the MSAL JS repo above.
