### ISSUE TITLE
How to send all the logs in to Frontend?

### ISSUE THREAD

**Issue by anjiuidev** [AzureAD/passport-azure-ad#493]
Hi all,

is there any way to send all the logs information to the client(browser), right now all the logs are showing in the console of command window.

Thanks.

**Comment by jennyf19** [comment]
@jasonnutter can you answer this one?

**Comment by jasonnutter** [comment]
@anjiuidev Since this is a middleware library that runs on the server, it is expected that the logs would show up in your console, as opposed to the browser, and there are no options in the library to enable that.

**Comment by anjiuidev** [comment]
@jasonnutter Thanks for your response, As you mentioned, I could able to see all the logs in the console, but my requirement is to show all the logs in the UI. Please suggest is there any workaround on this?

**Comment by jasonnutter** [comment]
@anjiuidev Unfortunately, I don't believe there are any possible workarounds in the library. There may be third-party libraries that will let you accomplish this, but I don't know any off-hand to recommend.
