### ISSUE TITLE
Outdated README.md

### ISSUE THREAD

**Issue by zd987** [AzureAD/passport-azure-ad#494]
The link mentioned in README.md https://apps.dev.microsoft.com/ is outdated, that webpage will show 

"Application registrations portal is no longer available to register and manage converged applications. We recommend that ​you manage your existing applications and register new applications by using the App registrations (now Generally Available) experience in the Azure portal. ​"

**Comment by jennyf19** [comment]
@mmacy is this something for you or someone else?

**Comment by mmacy** [comment]
@jennyf19 That'd be someone on the passport side.

**Comment by jennyf19** [comment]
@mmacy ok..we don't have anyone on that side at the moment. 
does this link seem to be the right one? I'll update the readme.
https://portal.azure.com/
@jmprieur

**Comment by mmacy** [comment]
@jennyf19 Use this one:

`https://aka.ms/appregistrations`

**Comment by jennyf19** [comment]
This has been fixed @zd987  thanks for bringing it to our attention.
