### ISSUE TITLE
Allow relative url to be configured for OIDCStrategy.redirectUrl

### ISSUE THREAD

**Issue by zahidma91** [AzureAD/passport-azure-ad#498]
OIDCStrategy.redirectUrl expects a fully qualified URL and fails validation if you provide a relative URL. This is inconvenient when we want the code to work in multiple environments where the host is not configured/known in code. Ideally we should be able to configure a relative url for redirectURL, and it should use the same host as the logic request.

Also, please let me know if anyone is aware of an alternative to this.

**Comment by nino-vrijman** [comment]
For anyone coming across this issue I posted a solution [here](https://github.com/AzureAD/passport-azure-ad/issues/516#issuecomment-792290137), similar to [#308](https://github.com/AzureAD/passport-azure-ad/issues/308#issuecomment-306023038).
