### ISSUE TITLE
Unauthorized Error on a valid token

### ISSUE THREAD

**Issue by azrulamir** [AzureAD/passport-azure-ad#500]
Hi,

Anyone here facing unathorized error all of a sudden since yesterday? Was there any changes on Azure that could cause this?

_**My MSAL Configuration.**_
`{
  auth: {
    clientId: process.env.VUE_APP_ADB2C_CLIENT_ID,
    redirectUri: process.env.VUE_APP_ADB2C_REDIRECT_URI,
    authority: process.env.VUE_APP_ADB2C_AUTHORITY_URL,
    validateAuthority: false
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: true
  }
}`

**_My Passport Azure AD options_**
`const options = {
  identityMetadata: 'https://xxx/xxx/xxx/v2.0/.well-known/openid-configuration',
  isB2C: true,
  policyName: 'xxx',
  clientID: 'xxx',
  validateIssuer: false,
  loggingLevel: 'info',
  loggingNoPII: false,
  passReqToCallback: false
};`

**Comment by nubianMONK** [comment]
Hi,

I started facing same issue as of 21st of August 2020. I have had this solution in place for a year with no issues, leveraging MSAL-Angular on the front end and Passport-Azure-AD on the server side via OIDCBearerStrategy to help authenticate and guard a custom API endpoint.

MSAL-Angular:
Using the V1 for the authority parameter: "https://login.microsoftonline.com/xxx.onmicrosoft.com/"

Passport-Azure-AD:
Using V1 : "https://login.microsoftonline.com/tenant_guid/.well-known/openid-configuration"

Any help with this, will be greatly appreciated.

**Comment by pkanher617** [comment]
We are currently in the design phase of a new version of this library, which can be tracked [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9). The timeline for the new library will be uploaded to our [msal js repo](https://github.com/AzureAD/microsoft-authentication-library-for-js).

Is this still an issue?

**Comment by sameerag** [comment]
Closing as no response. For any new issues, please raise them in the msal js repo mentioned above.

**Comment by nubianMONK** [comment]
@sameerag Still facing this issue please
