### ISSUE TITLE
How to get reason of token validation failure?

### ISSUE THREAD

**Issue by jefjos** [AzureAD/passport-azure-ad#505]
I have tried out this sample which uses passport-azure-ad - https://github.com/Azure-Samples/active-directory-javascript-nodejs-webapi-v2/blob/master/index.js
```

const bearerStrategy = new BearerStrategy(config, (token, done) => {
        // Send user info using the second argument
        done(null, {}, token);
    }
);

app.use(passport.initialize());

passport.use(bearerStrategy);

app.get("/hello",
    passport.authenticate('oauth-bearer', {session: false}),
    (req, res) => {
        console.log('User info: ', req.user);
.......
```

It works fine for valid token. however for any invalid token it always responds with 401 Unauthorized. I was wondering if there is any way of getting the actual reason for token validation failure - like expired token or invalid signature without implementing my custom validation logic and relying on the library's validation logic?

**Comment by rnarayana** [comment]
I am also looking for the same. I can view it in console if I set _loggingLevel_ to _info_ in the strategy config. But I havent found a way to send it back in response

**Comment by pkanher617** [comment]
We are currently only doing security fixes for this library. We are in the design phase of a new version of this library, which can be tracked [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9). The timeline for the new library will be uploaded to our [MSAL JS repo](https://github.com/AzureAD/microsoft-authentication-library-for-js). We will ensure to include this feedback in the upcoming design if applicable.
