### ISSUE TITLE
The configuration 'loggingNoPII' is overloaded

### ISSUE THREAD

**Issue by jefjos** [AzureAD/passport-azure-ad#506]
The configuration 'loggingNoPII' is overloaded. When set to true, it does not log PII, but it fails with generic message, and does not give out specific reason for token validation failure. 
The same configuration should not be used to control both logging and the messages given out by the library.

**Comment by pkanher617** [comment]
We are currently in the design phase of a new version of this library, which can be tracked [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9). The timeline for the new library will be uploaded to our [MSAL JS repo](https://github.com/AzureAD/microsoft-authentication-library-for-js). We will address logging as a whole in this design phase.
