### ISSUE TITLE
Property 'preferred_username' does not exist on type 'ITokenPayload'

### ISSUE THREAD

**Issue by DarkLite1** [AzureAD/passport-azure-ad#509]
### Description

The file `node_modules\@types\passport-azure-ad\common.d.ts` contains the following:
```js
export interface ITokenPayload {
    /** Only present in v2.0 tokens. The primary username that represents the user. It could be an email address, phone number, or a generic username without a specified format */
    preferred_name?: string;
}
```

The type `preferred_name` is not available on the access token and should be renamed to `preferred_username`.

Example of a correct access token:

```
Validated claims:  {
  aud: 'xxx-xxx-xxx-xxx-xxx',
  iss: 'https://login.microsoftonline.com/xxx-xxx-xxx-xxx-xxx/v2.0',
  iat: xxx,
  nbf: xxx,
  exp: xxx,
  aio: 'xxx/xxx/xxx/xxx',
  azp: 'xxx-xxx-xxx-xxx-xxx',
  azpacr: 'x',
  name: 'Bond, James (London) GBR',
  oid: 'xxx-xxx-xxx-xxx-xxx',
  preferred_username: 'James.Bond@mi6.co.uk',
  rh: 'x.xxx.',
  scp: 'xxx',
  sub: 'xxx',
  tid: 'xxx-xxx-xxx-xxx-xxx',
  uti: 'xxx',
  ver: '2.0'
}
```

### Error message
>  error TS2339: Property 'preferred_username' does not exist on type 'ITokenPayload'.

### Version
"passport-azure-ad": "^4.2.1"

### Code
```typescript
import { BearerStrategy, ITokenPayload } from 'passport-azure-ad'

new BearerStrategy( config,
  async (token: ITokenPayload, done: CallableFunction) => {
    console.log( token.preferred_username )
    return done(null, {}, token)
  }
)
```

**Comment by pkanher617** [comment]
@DarkLite1 I don't see this being exported from the passport-azure-ad library, is this available in the most recent release of passport-azure-ad?

**Comment by sameerag** [comment]
Closing as there is no response. 

Note: We are working on reviewing the remaining PRs in this repo. We are currently in the design phase of a new version of this library, which can be tracked [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9). The timeline for the new library will be uploaded to our [MSAL JS repo](https://github.com/AzureAD/microsoft-authentication-library-for-js).
