### ISSUE TITLE
Dynamic redirectUrl for two different domains

### ISSUE THREAD

**Issue by Mahan-F** [AzureAD/passport-azure-ad#516]
I have already looked at #308 #487 and #498 and i cant seem to find a solution to use a dynamic redirectUrl.

I have setup my AAD application to support redirect URL for two different domains. 

`https://domainOne.com/auth/openid/return`
`https://domainTwo.com/auth/openid/return`

Both these domains are pointing to the same server and same Node.js web application.

I need to be able to use the `req` (Express request object) to see the `Host` by `req.get('Host')` and then from there change the `redirectUrl` of passport accordingly so that users authenticating with `domainOne` are returned to `domainOne.com` domain and the same for `domainTwo` users.

Looking at the other issues I linked above, it seems like others are having the same issue but I didn't manage to find a solid working answers. Is this something that's possible?

**Comment by nino-vrijman** [comment]
It should be possible to set the redirect URL based on some data from the incoming request by doing something like this. I realize this is really similar the answer in #308 and as far as I can see it should work from version 3.0.5 and up. Make sure you're actually using `redirect_uri`, something different wouldn't work if I [see these lines](https://github.com/AzureAD/passport-azure-ad/blob/dev/lib/oidcstrategy.js#L1354-L1374). I successfully implemented this solution in a Nest.js project.

```JavaScript
app.get('/login', 
  (req, res, next) =>
    passport.authenticate('azure-ad', {
      extraAuthReqQueryParams: {
        redirect_uri: `https://${req.headers.host}/login/callback`,
      },
  })(req, res, next)
);
```

**Comment by sameerag** [comment]
Closing as #308 seems to resolve this issue. Please raise a new issue in our [mono repo](https://github.com/AzureAD/microsoft-authentication-library-for-js) if the given solution isn't feasible for any of your use cases.

**Comment by zettry1** [comment]
@nino-vrijman Hello,  I am using this solution and do need to set redirect url at callback request ?
`router.post(
  "/openid/return",
  (req, res, next) => {
    passport.authenticate("azuread-openidconnect", {
      response: res, // required
      failureRedirect: "/auth/reset",
      extraTokenReqQueryParams: {
        redirect_uri: `https://${req.headers.host}/openid/return`,
      },
    })(req, res, next);
  },
  (req, res) => {
    res.status(200).redirect("/menu");
  }
);`
