### ISSUE TITLE
Use BearerStrategy without middleware

### ISSUE THREAD

**Issue by reilem** [AzureAD/passport-azure-ad#520]
Is it possible to use the BearerStrategy without bulky middlewares? It's a shame this library forces devs to adopt a middleware based backend while (as far as I am aware) this is not at all necessary.

Unless I am mistaken, the core of the BearerStrategy authentication function really only takes an access token + options, and returns a validated access token. But currently if we want to call the `authenticate` function as a standalone we must pass the entire Request object to it, and then provide a custom callback to retrieve the user object. It would be nice to have this as a neat standalone function that takes just the access token, and just returns the validated user object (either in a promise or callback).

Reasons:

- This allows validation of access tokens anywhere in the code instead of only at endpoints, and allows devs to be more flexible in where and how they choose to validate the access_token
- It is quite reasonable to assume that not all node js backends use "passport" and middlewares. For example, in my case it is not possible to selectively verify GraphQL queries because all queries & mutations are accessed via the same endpoint. This means I need to implement a very hacky way of calling the middleware manually (see code example):
```
return new Promise((resolve) => {
  (passport.authenticate('oauth-bearer', { session: false }, async (_1, _2, _3, user) => {
    resolve(user || null)
  }))(req, rep)
})
```

If this proposal violates some sort of security principle then I understand that this isn't possible. But as far as I can see there shouldn't be anything holding us back from just implementing a separate standalone authentication function that doesn't require `Request` and `Response` objects.

**Comment by sameerag** [comment]
@reilem Yes, feedback noted. We are currently in the design phase of a new version of this library, which can be tracked [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9). The timeline for the new library will be uploaded to our [msal js repo](https://github.com/AzureAD/microsoft-authentication-library-for-js).

This new library will be based on our current [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node) library and decoupling passport strategies from the middleware functionality is one of the key design aspects we are considering.

Please let us know if you have more feedback in our new repo. Closing this.
