### ISSUE TITLE
Error Handling and Token Validation

### ISSUE THREAD

**Issue by valentinyanakiev** [AzureAD/passport-azure-ad#521]
I would like to see better validation and error handling in the strategies. I am working on a cloud-first application and I am building nestJS back-end for it and supporting all meaningful scenarios is REALLY difficult, I'd say even impossible, as is.

   - Using Bearer Strategy in the backend. After an Access Token is received, if the token is expired and PII is not logged, a generic error is thrown and not 'jwt is expired'. So what is the course of action here, to log PII for thousands, tens of thousands of users because you assume 'jwt is expired' contains PII? In a GDPR world? I see no relation between PII and verbose logging, these are separate topics and should be dealt with independently. I'd suggest adding something like validation_level logging.
   - having a React Client (or any client really) relying on the information when a token is expired is common practice and there is no way that can be done with the current error propagation of your strategies.
   - verbose validation and logging has nothing to do with PII. I see many places in your code where you don't log something checking whether PII logging is enabled, where the output has absolutely nothing to do with PII. That's wrong.

**Comment by sameerag** [comment]
We are currently in the design phase of a new version of this library, which can be tracked [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9). The timeline for the new library will be uploaded to our [msal js repo](https://github.com/AzureAD/microsoft-authentication-library-for-js).

We will consider this feedback in the new version of our library. We are basing the new library on [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node) which should address most of the error management and logging issues mentioned above.

Please open an issue on the new repo in case you have any more feedback.
