### ISSUE TITLE
How to get access token please?

### ISSUE THREAD

**Issue by peterfeng-hub** [AzureAD/passport-azure-ad#525]
I'm using OIDCStrategy. I can use `passport.authenticate()` to get the `user` object without any problem. 

What I'm trying to do is to call a Microsoft Graph API under the OIDCStrategy. Can you please advise if it's possible? I'm struggling to get the access token that is needed to call any Microsoft Graph API, but haven't got a clue on how to get that.

Your guidance will be much appreciated!

**Comment by MartinListwan** [comment]
Did you figure out how?

**Comment by peterfeng-hub** [comment]
No I still haven’t.

________________________________

**Comment by sameerag** [comment]
@peterfeng-hub Can you take a look at our [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node) library and see if that helps your use case?

We are currently in the design phase of a new version of the passport-azure-ad library, which can be tracked [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9). The timeline for the new library will be uploaded to our [msal js repo](https://github.com/AzureAD/microsoft-authentication-library-for-js).
