### ISSUE TITLE
Authenticating against invited guest accounts in Azure AD does not work using v2 tenant-specific endpoint  

### ISSUE THREAD

**Issue by anthonywoodard** [AzureAD/passport-azure-ad#528]
passport v0.4.1
passport-azure-ad v4.2.1
The metadata endpoint we are using is https://login.microsoftonline.com/{tenant_id}/v2.0/.well-known/openid-configuration.
Authenticating with the v2 endpoint works for our new federated guest accounts in Azure AD but not older invited guest accounts such as Yahoo, Netscape, etc.  The v1 endpoint does not work for new federated guest accounts in Azure AD like new Google accounts but does work for older invited guest accounts. 
We have some older invited guest accounts but our new guest accounts are federated. How can the v2 endpoint be used to authenticate the older invited guest accounts?

**Comment by jasonnutter** [comment]
@anthonywoodard Have you tried using the v2 common endpoint? `https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration`

**Comment by anthonywoodard** [comment]
No, I have not tried the common endpoint.  How do you identify the tenant using the common endpoint?  Or is that even an issue?

**Comment by jasonnutter** [comment]
@anthonywoodard Sorry, common endpoint wouldn't work for guests. Do you have any correlation ids or network traces (e.g. Fiddler) you can share? My email is in my profile, thanks!

**Comment by hpsin** [comment]
The V2 and V1 tenanted endpoints should both work correctly.  Can you share the sign in URLs that work in both cases? We'll need the domain+path of the request, as well as the client ID, so that we can check these in our logs (all of this is non-confidential data). 

One note, to see if it helps - since you're signing in guests, it's critical that you do use a tenanted endpoint, so you should see e.g. login.microsoftonline.com/yourTenant.com/oauth2/v2.0/authorize .  Otherwise we can't figure out what tenant we should sign the guest into.

**Comment by anthonywoodard** [comment]
@hpsin The v2 identitymetadata URL we use is https://login.microsoftonline.com/22340fa8-9226-4871-b677-d3b3e377af72/v2.0/.well-known/openid-configuration. The v1 URL is https://login.microsoftonline.com/22340fa8-9226-4871-b677-d3b3e377af72/.well-known/openid-configuration.  The client ID is 02534573-4990-4399-baa5-b494db708066.  Is this what you are looking for?

**Comment by hpsin** [comment]
Almost - thanks! Can you confirm that when the user is actually signing in, the URL in the sign in page matches that value?  https://login.microsoftonline.com/22340fa8-9226-4871-b677-d3b3e377af72/oauth2/v2.0/authorize?

**Comment by sameerag** [comment]
@anthonywoodard Is this still an issue?
@hpsin Any update?

**Comment by hpsin** [comment]
@anthonywoodard  if you can share the token contents of the new users, that would be really helpful! In addition, where you're getting the token from.

**Comment by anthonywoodard** [comment]
> @anthonywoodard Is this still an issue?
> @hpsin Any update?

Both older invited guest accounts and federated guest account authentication are working.  There was a point in the process where we were using a v1 endpoint.  After ensuring that v2 endpoints are used throughout, authentication worked and we are able to use the derived token with the MS Graph API.  Thank you for your help.

**Comment by sameerag** [comment]
Thank you for getting back. Closing this.
