### ISSUE TITLE
Can't find responseMode=fragment

### ISSUE THREAD

**Issue by lflescano** [AzureAD/passport-azure-ad#530]
Hi, im seeing in azure documentation that there is a responseMode=fragment so i can receive code and id_token. It looks like is not supported in here? How could i fix it, i need both parameters in query mode at least, like queryparams

Thanks

**Comment by lflescano** [comment]
So, i add yo this function the fragment option, and it works fine, like i want to. When do you think this will be available

Validator.isModeLegal = 'isModeLegal';
types.isModeLegal = {
  validate: (value) => {
    return value === 'query' || value === 'form_post' || value === 'fragment';
  },
  error: 'The responseMode: must be either query or form_post.',
};

**Comment by jasonnutter** [comment]
Can you please clarify your use case? The value of the url hash/fragment is not transmitted to servers (it is only available in client-side code, e.g. MSAL.js), which is why query and form_post are the two allowed responseModes.

**Comment by sameerag** [comment]
Browser use cases (OpenID strategy) can theoretically support this. Please follow our new library to track this.

We are currently in the design phase of a new version of this library, which can be tracked [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9). The timeline for the new library will be uploaded to our [msal js repo](https://github.com/AzureAD/microsoft-authentication-library-for-js).
