### ISSUE TITLE
Serverless usage

### ISSUE THREAD

**Issue by sandanarajeev** [AzureAD/passport-azure-ad#532]
I'm using Azure Functions(Server-less Arch). Is it possible to use passport aad with server-less Arch ? I know its possible to run an express server in a function and use passport over there, but it contradicts the server-less architecture. Any other solutions ? 

@xerners

**Comment by derisen** [comment]
@sandanarajeev there's a 3rd party library, [azure-function-express](https://www.npmjs.com/package/azure-function-express) that converts your express code. You can see how its used in [this sample](https://github.com/Azure-Samples/ms-identity-nodejs-webapi-azurefunctions). Bear in mind this is more of a hack and doesn't support v3 functions.

**Comment by derisen** [comment]
Closing.
