### ISSUE TITLE
[ENHANCEMENT] Allow consuming applications to configure a logging adapter

### ISSUE THREAD

**Issue by Drew-Kimberly** [AzureAD/passport-azure-ad#548]
### Problem
Our infra platform's log forwarder listens to a mounted directory where our application writes structured NDJSON log messages. Given that this library's logging utility only outputs to stdout/err, we are flying blind in deployed environments when issues like JWT validation occur.

### Proposal
1. Expose a `Logger` type and an optional config property to `OIDCStrategy` and `BearerStrategy` that enables consuming applications to pass in a reference to a logger that satisfies the `Logger` type.
2. Update the `logger` utility to first check for the existence of a configured logger prior to using the default Bunyan logger.

**Comment by Drew-Kimberly** [comment]
I (my team) would be interested in contributing this feature, if approved!

**Comment by tnorling** [comment]
@Drew-Kimberly This library is currently in maintenance phase and we are taking only security bugs.

We are currently in the design phase of a new version of this library, which will live in the MSAL.js monorepo and can be tracked [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9). The timeline for the new library will be uploaded to our [msal js repo](https://github.com/AzureAD/microsoft-authentication-library-for-js) as soon as it's ready to share. This feature request will almost certainly be included in that new library as our other libraries implement a similar pattern but if you'd like to track this item specifically I'd suggest opening a feature request on that repo. Thanks!

**Comment by Drew-Kimberly** [comment]
Thanks @tnorling! Referencing https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3256 as it covers the feature req 👍
