### ISSUE TITLE
Scope seperator undefined.

### ISSUE THREAD

**Issue by sedouard** [AzureAD/passport-azure-ad#61]
The scope seperator is undefined if you add for example a scope array in passport.use like below:

{
    callbackURL: nconf.get('returnURL'),
    realm: nconf.get('realm'),
    clientID: nconf.get('clientID'),
    clientSecret: nconf.get('clientSecret'),
    identityMetadata: nconf.get('identityMetadata'),
    responseType: nconf.get('responseType'),
    responseMode: nconf.get('responseMode'),
    skipUserProfile: nconf.get('skipUserProfile'),
    scope: ['https://outlook.office.com/calendars.read']
};

The result is something like this:
<img width="1487" alt="screen shot 2015-10-07 at 3 41 02 pm" src="https://cloud.githubusercontent.com/assets/3053263/10353259/da2263ce-6d09-11e5-9e2c-bba64a182eb2.png">

The issue seems to be a mismatch in variable names `_scopeSeperator` and `scopeSeperator`. Its [undefined here](https://github.com/AzureAD/passport-azure-ad/blob/master/lib/passport-azure-ad/oidcstrategy.js#L496).

@mzxgiant actually spotted this one. Is this a known issue? Otherwise we'll be happy to provide a PR

**Comment by brandwe** [comment]
Thanks for the report and the fix! :100:
