### ISSUE TITLE
Possible typo in OIDCStrategy.js

### ISSUE THREAD

**Issue by jeffwilcox** [AzureAD/passport-azure-ad#67]
Running into a few potential issues in OIDCStrategy.js... updating as I find others.

# Part 1

In this line:
https://github.com/AzureAD/passport-azure-ad/blob/master/lib/passport-azure-ad/oidcstrategy.js#L487

There is this code:

```
log.info("Going in with our config loaded as: ", config);

      var params = self.authorizationParams(options);
      var params = {};
      params['response_type'] = config.responseType;

```

Is params a copy/paste error, or is it supposed to empty it out as soon as retrieving, or ... ? I wasn't sure which to do here or else I would have opened a PR with a change/fix. I assume the `params = {}` code is incorrect.

# Part 2

This line: https://github.com/AzureAD/passport-azure-ad/blob/master/lib/passport-azure-ad/oidcstrategy.js#L619

tokenURL is set twice in this body...

```
 var config = { 
         clientID: Validator.isNonEmpty, 
         callbackURL: Validator.isNonEmpty, 
         tokenURL: Validator.isNonEmpty, 
         responseType: Validator.isTypeLegal, 
         responseMode: Validator.isModeLegal, 
         authorizationURL: Validator.isURL, 
         tokenURL: Validator.isURL 
        // callbackURL: Validator.isURL  // We allow http for now :-/ 
     }; 
 
 
```

**Comment by brandwe** [comment]
Already fixed in /dev branch.
