### ISSUE TITLE
passReqToCallback with OIDCStrategy

### ISSUE THREAD

**Issue by alpeshgaglani** [AzureAD/passport-azure-ad#73]
Hi,
I am trying to follow the examples and use OIDCStrategy to integrate with AzureAD. If I follow the examples, as is, things work just fine. However, when I specify the passReqCallback = true, I don't get my request passed back. 
Here's my OIDCStrategy code:
(passport.use(new OIDCStrategy({
      callbackURL: config.azureadCreds.callbackURL,
      realm: config.azureadCreds.realm,
      clientID: config.azureadCreds.clientID,
      clientSecret: config.azureadCreds.clientSecret,
      //oidcIssuer: config.azureadCreds.issuer,
      identityMetadata: config.azureadCreds.identityMetadata,
      skipUserProfile: config.azureadCreds.skipUserProfile,
      responseType: config.azureadCreds.responseType,
      responseMode: config.azureadCreds.responseMode,
      passReqToCallback: true
    },
    function (req, iss, sub, profile, accessToken, refreshToken, done) {
      console.log("profile: " + util.inspect(profile));
    }
  )))
In this case, the argument list is the exact same if passReqToCallback was not specified. (i.e. req parameter is the issuer, iss is sub etc..)
Is there something I'm missing?

**Comment by brandwe** [comment]
Fixed in #82
