### ISSUE TITLE
OIDCStrategy doesnt pass state 

### ISSUE THREAD

**Issue by alpeshgaglani** [AzureAD/passport-azure-ad#74]
I see that lines 556 and 557 in oidcstrategy.js are commented out - this prevents the state parameter to be passed back to the callback object. Our code-base relies on retrieving this information. Is there a reason for those to be omitted?

**Comment by gbockus** [comment]
:+1:   The state param should be supported for all strategies.  Its usage is recommended in the azure OAuth2 best practices: https://msdn.microsoft.com/en-us/library/azure/dn645536.aspx

**Comment by brandwe** [comment]
I could have sworn I stopped this for a reason, something about the state breaking B2C flows - but if it should be there for B2B scenarios I can do a conditional. I'll do some testing and see if it works.

**Comment by brandwe** [comment]
Yes, looking at code in dev branch it says: 

     // var state = utils.uid(16); no longer used in OpenID Connect flows. I'll try to get info on this from the team on the current best practices.

**Comment by brandwe** [comment]
Looking at this, it appears we now pass as `nonce` and not `state`. So you'll only get back the nonce from the server.

**Comment by brandwe** [comment]
Fixed in #82. Will most likely undo though.
