### ISSUE TITLE
OICDstrategy does not return a bearer token

### ISSUE THREAD

**Issue by TotallyInformation** [AzureAD/passport-azure-ad#75]
Hi, I'm afraid I'm rather a beginner in the world of OAuth programming so please bear with me.

I successfully used this module to connect to Azure AD. However, I don't seem to get back the information needed to then actually USE it?

I am trying to connect to SharePoint Online to pull down the groups used for a specific site: ```_api/web/roleassignments/groups```

But this requires an Authorization header to be set which I think should be the OAuth Bearer token. I can see that in the debug output from ```oidcstrategy.js``` ```oauth2.getOAuthAccessToken``` but I can't quite work out how to make it available back to my app.

However, surely I shouldn't need to? Shouldn't this module expose all of the information required to actually use things?

It really would be most helpful for Microsoft to supply an actual working example - one that did something useful rather than the examples using this library which only seem to cover connecting and not using.

**Comment by TotallyInformation** [comment]
This question on Stack seems to point the way to the answer but my detailed knowledge isn't sufficient to work it out - SO frustrating that there is no worked out example of being able to use Node.JS to actually do something via the graph api's that requires user auth.

**Comment by brandwe** [comment]
Hello @TotallyInformation - the sample does show how to get a token and then supply that token to a REST API. However that REST API is also a sample and not the Office graph. I think your question is actually how to query the Office graph with node.js? You may find this helpful: https://github.com/OfficeDev/O365-Nodejs-Microsoft-Graph-Connect

**Comment by brandwe** [comment]
Closing for hygiene. If you have more questions open it up again. I'd be interested if you got the Graph API to work.

**Comment by stevenfollis** [comment]
Ran into this same problem today. The referenced sample ( https://github.com/OfficeDev/O365-Nodejs-Microsoft-Graph-Connect) does not appear to use the `passport-azure-ad` library and instead is using `oauth` + helpers.  Was unable to use OIDC with passport-azure-ad to get a token; would love a sample. Thanks!

**Comment by brandwe** [comment]
@stevenfollis Thanks for the feedback. You should ask the maintainer of that repo to use `passport-azure-ad` as they control the dependencies of the sample.
