### ISSUE TITLE
Incorrectly typed module reference hiding actual test failures

### ISSUE THREAD

**Issue by ryanvog** [AzureAD/passport-azure-ad#76]
`oidc_tests.js`

`[21] var OidcStrategy = require('../lib/passport-azure-ad/index').OIDCStrategy;`

However, in most of the tests, this is how the object is constructed:
```
function () {
  new OIDCStrategy(oidcConfig, function () { });
}
```

`OIDCStrategy` is incorrectly cased, resulting in a ReferenceError, which is caught by the assertion and treated as a PASS.

It should be:
```
function () {
  new OidcStrategy(oidcConfig, function () { });
}
```
However, constructing a new `OidcStrategy` does not presently invoke the options validation, resulting in no exception thrown.

All but the last test in this test class exhibit this incorrect casing issue.

**Comment by brandwe** [comment]
@ryanvog I fixed the casing but can you explain how it doesn't invoke options validation? I do two tests, one without options which fails (which is a PASS) and one which provides options which if is successful is a PASS

```    'no args': function(test) {
        test.expect(1);
        // tests here

        test.throws(
            function() {
                new OIDCStrategy();
            },
            Error,
            'Should fail with no arguments)'
        );

        test.done();
    },

    'with options': function(test) {
        test.expect(1);
        // tests here

        var oidcConfig = {
            // required options
            identityMetadata: 'https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration',
            responseType: 'id_token', // for login only flows use id_token. For accessing resources use `id_token code`
            responseMode: 'form_post', // For login only flows we should have token passed back to us in a POST
        };

        test.doesNotThrow(
            function() {
                new OIDCStrategy(oidcConfig, function() {});
            },
            Error,
            'Should not fail with proper v2 OIDC config options'
        );

        test.done();
    }
```

Also keep in mind I have different params for v2 and odic and each should fail on different values that aren't workable.

**Comment by brandwe** [comment]
Fixed

**Comment by ryanvog** [comment]
Thanks for looking into this @brandwe.  WRT the options validation, there are two areas options appear to be validated.  Some options are validated in the constructor function for OIDCStrategy, and others are validated during the call to setOptions(), as a result of a call to `authenticate`.  You have tests that validate both, but in the latter case, since `setOptions` isn't being invoked, there is no validation for the following tests:

```
'with missing option resposneType'
'with missing option resposneMode'
```
In each of these tests, responseType and responseMode are validated, but the validation for these fields only occurs in the call to setOptions().

Hope this helps
