### ISSUE TITLE
DEV is not LINT-clean

### ISSUE THREAD

**Issue by ryanvog** [AzureAD/passport-azure-ad#78]
Run `grunt` in the root of the repo and you will get several pages of JSHINT errors. The contribution section of the `readme` indicates that contributions should be LINTed.

**Comment by brandwe** [comment]
Appears that my linter in Sublime Text 3 wasn't running as I needed to configure the PATH (even though it is found in my terminal's PATH). I finally sees these now and will get to fixing some of them. line breaks, etc. I'm not going to mess with.
