### ISSUE TITLE
TypeError: this.fail is not a function

### ISSUE THREAD

**Issue by julianfrank** [AzureAD/passport-azure-ad#91]
I'm having a NodeJS App and am using your module to integrate authentication with azure AD...Everything is cozy with 'assigned' users. 

I get this error whenever I try to login into my app with an 'Un-Assigned User' ...As per Passport documentation this should route the page back to login page but in my app this error is thrown and the application exits!...Could you please suggest how I should work around this?

**Here is the dump in NodeJS:**
TypeError: this.fail is not a function
    at d:\Users\Johan\Documents\CloudCode\jfwrtc\node_modules\passport-azure-ad\lib\passport-azure-ad\oidcstrategy.js:174:17
    at fn (d:\Users\Johan\Documents\CloudCode\jfwrtc\node_modules\async\lib\async.js:746:34)
    at d:\Users\Johan\Documents\CloudCode\jfwrtc\node_modules\async\lib\async.js:1213:16
    at d:\Users\Johan\Documents\CloudCode\jfwrtc\node_modules\async\lib\async.js:166:37
    at d:\Users\Johan\Documents\CloudCode\jfwrtc\node_modules\async\lib\async.js:706:43
    at d:\Users\Johan\Documents\CloudCode\jfwrtc\node_modules\async\lib\async.js:167:37
    at d:\Users\Johan\Documents\CloudCode\jfwrtc\node_modules\async\lib\async.js:1209:30
    at d:\Users\Johan\Documents\CloudCode\jfwrtc\node_modules\passport-azure-ad\lib\passport-azure-ad\oidcstrategy.js:157:10
    at d:\Users\Johan\Documents\CloudCode\jfwrtc\node_modules\passport-azure-ad\lib\passport-azure-ad\oidcstrategy.js:735:13
    at d:\Users\Johan\Documents\CloudCode\jfwrtc\node_modules\async\lib\async.js:52:16
    at Immediate.<anonymous> (d:\Users\Johan\Documents\CloudCode\jfwrtc\node_modules\async\lib\async.js:1206:34)
    at Immediate.wrapped [as _onImmediate] (d:\Users\Johan\Documents\CloudCode\jfwrtc\node_modules\newrelic\lib\transaction\tracer\index.js:155:28)
    at processImmediate [as _immediateCallback] (timers.js:516:17)

**Here is the POST I receive from Azure AD**...Which is as per expectation for un-assigned users:
/oauth2return?error=access_denied&error_description=AADSTS50105%3a+The+signed+in+user+%27user2%40jfkalab.onmicrosoft.com%27+is+not+assigned+to+a+role+for+the+application+%277a4c6cd6-7116-4cb3-abe3-d311345149c6%27.%0d%0aTrace+ID%3a+341cf1bb-b20e-4f53-8267-1caa81f349ce%0d%0aCorrelation+ID%3a+8dfe7c6d-5939-4788-ad90-3c7cc922be88%0d%0aTimestamp%3a+2016-03-23+15%3a29%3a04Z&state=lsQpX2qYHZkNKJaA

**Comment by brandwe** [comment]
Ahh so the problem is I don't have a failure case that does the right thing I believe. I can work on this and have a fix by EOW. Thanks for the issue!

**Comment by julianfrank** [comment]
Just came across this just now...Looks like its not implemented in the current update yet...

**Comment by lovemaths** [comment]
done
